from django.urls import path

from .views import (
    AdminAuditListView, AdminDashboardView, AdminSystemHealthView, AdminTaskListView,
    AgentRunListView, CandidateAccountActionView, CandidateAccountDetailView, CandidateAccountListView,
    CandidateBreakGlassView, KnowledgeReviewDecisionView,
    KnowledgeReviewListView, ModelGatewaySummaryView, ModerationReportDecisionView,
    ModerationReportListView, PrivacyRequestDecisionView, PrivacyRequestListView,
    StaffAccountActionView, StaffAccountDetailView, StaffAccountListCreateView, StaffCsrfView,
    StaffInvitationActionView, StaffInvitationActivateView, StaffInvitationDetailView,
    StaffInvitationRegisterView, StaffLoginView,
    StaffLogoutView, StaffRoleListView, StaffSecuritySetupView, StaffSessionView,
)
from .operations_views import (
    AdminTaskActionView, AgentRunAdminDetailView, AnalyticsAdminView, ContentOperationsAdminView,
    FeatureFlagAdminDetailView, FeatureFlagAdminView, GatewayResourceAdminDetailView,
    GatewayResourceAdminView, InterviewConfigAdminView, InterviewSessionAdminActionView,
    InterviewSessionAdminDetailView, InterviewSessionAdminListView, KnowledgeChunkDraftActionView,
    KnowledgeChunkDraftAdminView, KnowledgeDocumentAdminActionView, KnowledgeReviewAdminDetailView,
    MaintenanceNoticeAdminView, NotificationOperationsAdminView,
    ResilienceMetricsAdminView,
)
from .agent_config_views import (
    AgentConfigExperimentView,
    AgentConfigEvaluationDatasetView,
    AgentConfigProfileRevisionView,
    AgentConfigProfileView,
    AgentConfigResolvedPreviewView,
    AgentConfigRevisionActionView,
    AgentConfigRevisionView,
    AgentPromptPreviewView,
    KnowledgeBaseRevisionView,
    KnowledgeBaseView,
    RetrievalProfileActionView,
    RetrievalProfileView,
)
from .platform_views import (
    CareerConfigAdminView,
    CommunityModerationAdminView,
    CompanyReviewAdminView,
    JobReviewAdminView,
    PlatformEventsAdminView,
    ReliabilityAdminView,
    ResumeConfigAdminView,
)


urlpatterns = [
    path('auth/csrf/', StaffCsrfView.as_view()),
    path('auth/login/', StaffLoginView.as_view()),
    path('auth/security-setup/', StaffSecuritySetupView.as_view()),
    path('auth/activate/', StaffInvitationActivateView.as_view()),
    path('auth/invitations/<str:token>/', StaffInvitationDetailView.as_view()),
    path('auth/register/', StaffInvitationRegisterView.as_view()),
    path('auth/session/', StaffSessionView.as_view()),
    path('auth/logout/', StaffLogoutView.as_view()),
    path('dashboard/summary/', AdminDashboardView.as_view()),
    path('staff/', StaffAccountListCreateView.as_view()),
    path('staff-invitations/', StaffAccountListCreateView.as_view()),
    path('staff/<uuid:account_id>/', StaffAccountDetailView.as_view()),
    path('staff/<uuid:account_id>/<str:action>/', StaffAccountActionView.as_view()),
    path('staff-invitations/<uuid:invitation_id>/<str:action>/', StaffInvitationActionView.as_view()),
    path('staff/roles/', StaffRoleListView.as_view()),
    path('knowledge-reviews/', KnowledgeReviewListView.as_view()),
    path('knowledge-reviews/<uuid:document_id>/', KnowledgeReviewAdminDetailView.as_view()),
    path('knowledge-reviews/<uuid:document_id>/<str:decision>/', KnowledgeReviewDecisionView.as_view()),
    path('knowledge-documents/<uuid:document_id>/<str:action>/', KnowledgeDocumentAdminActionView.as_view()),
    path('knowledge-chunk-drafts/<uuid:chunk_id>/', KnowledgeChunkDraftAdminView.as_view()),
    path('knowledge-chunk-drafts/<uuid:chunk_id>/<str:action>/', KnowledgeChunkDraftActionView.as_view()),
    path('interviews/', InterviewSessionAdminListView.as_view()),
    path('interviews/<uuid:session_id>/', InterviewSessionAdminDetailView.as_view()),
    path('interviews/<uuid:session_id>/<str:action>/', InterviewSessionAdminActionView.as_view()),
    path('agent-runs/', AgentRunListView.as_view()),
    path('agent-runs/<uuid:run_id>/', AgentRunAdminDetailView.as_view()),
    path('interview-config/<str:resource>/', InterviewConfigAdminView.as_view()),
    path('agent-config/profiles/', AgentConfigProfileView.as_view()),
    path('agent-config/profiles/<uuid:profile_id>/revisions/', AgentConfigProfileRevisionView.as_view()),
    path('agent-config/revisions/<uuid:revision_id>/', AgentConfigRevisionView.as_view()),
    path('agent-config/revisions/<uuid:revision_id>/resolved-preview/', AgentConfigResolvedPreviewView.as_view()),
    path('agent-config/revisions/<uuid:revision_id>/<str:action>/', AgentConfigRevisionActionView.as_view()),
    path('agent-config/prompts/<path:task_key>/preview/', AgentPromptPreviewView.as_view()),
    path('agent-config/experiments/retrieval/', AgentConfigExperimentView.as_view()),
    path('agent-config/evaluation-datasets/', AgentConfigEvaluationDatasetView.as_view()),
    path('knowledge-bases/', KnowledgeBaseView.as_view()),
    path('knowledge-bases/revisions/<uuid:revision_id>/', KnowledgeBaseRevisionView.as_view()),
    path('retrieval-profiles/', RetrievalProfileView.as_view()),
    path('retrieval-profiles/revisions/<uuid:revision_id>/<str:action>/', RetrievalProfileActionView.as_view()),
    path('model-gateway/summary/', ModelGatewaySummaryView.as_view()),
    path('model-gateway/<str:resource>/', GatewayResourceAdminView.as_view()),
    path('model-gateway/<str:resource>/<int:object_id>/', GatewayResourceAdminDetailView.as_view()),
    path('tasks/', AdminTaskListView.as_view()),
    path('tasks/<uuid:operation_id>/<str:action>/', AdminTaskActionView.as_view()),
    path('system/readiness/', AdminSystemHealthView.as_view()),
    path('system/resilience/', ResilienceMetricsAdminView.as_view()),
    path('candidates/', CandidateAccountListView.as_view()),
    path('candidates/<int:candidate_id>/', CandidateAccountDetailView.as_view()),
    path('candidates/<int:candidate_id>/break-glass/', CandidateBreakGlassView.as_view()),
    path('candidates/<int:candidate_id>/<str:action>/', CandidateAccountActionView.as_view()),
    path('privacy-requests/', PrivacyRequestListView.as_view()),
    path('privacy-requests/<int:request_id>/<str:decision>/', PrivacyRequestDecisionView.as_view()),
    path('moderation/reports/', ModerationReportListView.as_view()),
    path('moderation/reports/<int:report_id>/<str:decision>/', ModerationReportDecisionView.as_view()),
    path('content/operations/', ContentOperationsAdminView.as_view()),
    path('notifications/operations/', NotificationOperationsAdminView.as_view()),
    path('analytics/', AnalyticsAdminView.as_view()),
    path('feature-flags/', FeatureFlagAdminView.as_view()),
    path('feature-flags/<int:flag_id>/', FeatureFlagAdminDetailView.as_view()),
    path('maintenance-notices/', MaintenanceNoticeAdminView.as_view()),
    path('audit-logs/', AdminAuditListView.as_view()),
    path('career-config/', CareerConfigAdminView.as_view()),
    path('resume-config/', ResumeConfigAdminView.as_view()),
    path('companies/', CompanyReviewAdminView.as_view()),
    path('companies/<uuid:company_id>/<str:decision>/', CompanyReviewAdminView.as_view()),
    path('jobs/', JobReviewAdminView.as_view()),
    path('jobs/<uuid:job_id>/<str:decision>/', JobReviewAdminView.as_view()),
    path('community/moderation/', CommunityModerationAdminView.as_view()),
    path('community/moderation/<uuid:case_id>/<str:decision>/', CommunityModerationAdminView.as_view()),
    path('operations/events/', PlatformEventsAdminView.as_view()),
    path('operations/events/<uuid:event_id>/replay/', PlatformEventsAdminView.as_view()),
    path('reliability/', ReliabilityAdminView.as_view()),
]
