# Generated by Django 5.0.3 on 2025-09-23 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模型显示名称')),
                ('model_slug', models.CharField(max_length=100, unique=True, verbose_name='模型调用标识')),
                ('base_url', models.URLField(max_length=255, verbose_name='API Base URL')),
                ('description', models.TextField(blank=True, verbose_name='模型描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': 'AI 模型',
                'verbose_name_plural': 'AI 模型',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='行业名称')),
                ('description', models.TextField(blank=True, verbose_name='行业描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '行业分类',
                'verbose_name_plural': '行业分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='岗位名称')),
                ('description', models.TextField(blank=True, verbose_name='岗位描述')),
                ('icon_svg', models.TextField(blank=True, verbose_name='图标 SVG 代码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '面试岗位',
                'verbose_name_plural': '面试岗位',
                'ordering': ['industry__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AISetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ai_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.aimodel', verbose_name='AI 模型')),
            ],
            options={
                'verbose_name': 'AI 设置',
                'verbose_name_plural': 'AI 设置',
            },
        ),
    ]
