# Generated by Django 5.0.3 on 2025-09-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='岗位名称')),
                ('description', models.TextField(blank=True, verbose_name='岗位描述')),
                ('icon_svg', models.TextField(blank=True, verbose_name='图标 SVG 代码')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '面试岗位',
                'verbose_name_plural': '面试岗位',
                'ordering': ['order', 'name'],
            },
        ),
    ]
