# Generated by Django 5.0.3 on 2025-10-19 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aisetting',
            name='api_key',
        ),
        migrations.AddField(
            model_name='aisetting',
            name='api_keys',
            field=models.JSONField(blank=True, default=dict, verbose_name='API Keys 映射'),
        ),
        migrations.AlterField(
            model_name='aisetting',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.aimodel', verbose_name='默认AI模型'),
        ),
    ]
