# Generated by Django 5.0.3 on 2025-09-22 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_jobposition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='行业名称')),
                ('description', models.TextField(blank=True, verbose_name='行业描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '行业分类',
                'verbose_name_plural': '行业分类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'ordering': ['industry__order', 'order', 'name'], 'verbose_name': '面试岗位', 'verbose_name_plural': '面试岗位'},
        ),
        migrations.AddField(
            model_name='jobposition',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_positions', to='system.industry', verbose_name='所属行业'),
        ),
    ]
