# Generated by Django 5.0.3 on 2025-10-19 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_remove_aisetting_api_key_aisetting_api_keys_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='supports_json_mode',
            field=models.BooleanField(default=True, verbose_name='支持 JSON 模式'),
        ),
    ]
