# Generated by Django 5.0.3 on 2025-09-22 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_industry_alter_jobposition_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, verbose_name='模型显示名称')),
                ('model_name', models.CharField(max_length=100, unique=True, verbose_name='模型标识符')),
                ('api_base_url', models.URLField(verbose_name='API Base URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': 'AI 模型',
                'verbose_name_plural': 'AI 模型',
                'ordering': ['order'],
            },
        ),
    ]
