# Generated by Django 5.0.3 on 2025-09-22 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_aimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisetting',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.aimodel', verbose_name='AI 模型'),
        ),
    ]
