# Generated by Django 5.2.7 on 2026-06-26 15:48

import django.db.models.deletion
from django.db import migrations, models


def seed_enterprise_ai_models(apps, schema_editor):
    AIModel = apps.get_model('system', 'AIModel')
    defaults = [
        {
            'name': 'DeepSeek Chat',
            'model_slug': 'deepseek-chat',
            'base_url': 'https://api.deepseek.com',
            'provider': 'deepseek',
            'model_type': 'chat',
            'description': '系统默认对话模型',
            'supports_json_mode': True,
        },
        {
            'name': '阿里云 text-embedding-v3',
            'model_slug': 'text-embedding-v3',
            'base_url': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
            'provider': 'aliyun_dashscope',
            'model_type': 'embedding',
            'description': '阿里云百炼通用文本向量模型',
            'supports_json_mode': False,
            'dimension': 1024,
        },
        {
            'name': '阿里云 qwen-rerank',
            'model_slug': 'qwen-rerank',
            'base_url': 'https://dashscope.aliyuncs.com/api/v1/services/rerank/text-rerank/text-rerank',
            'provider': 'aliyun_dashscope',
            'model_type': 'rerank',
            'description': '阿里云百炼文本重排模型',
            'supports_json_mode': False,
        },
    ]
    for item in defaults:
        AIModel.objects.update_or_create(
            model_slug=item['model_slug'],
            defaults={**item, 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_aimodel_supports_json_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='dimension',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='向量维度'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('chat', '对话模型'), ('embedding', 'Embedding模型'), ('rerank', 'Rerank模型')], db_index=True, default='chat', max_length=20, verbose_name='模型类型'),
        ),
        migrations.AddField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(default='openai_compatible', max_length=50, verbose_name='模型供应商'),
        ),
        migrations.AddField(
            model_name='aisetting',
            name='chat_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'model_type': 'chat'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_settings', to='system.aimodel', verbose_name='默认对话模型'),
        ),
        migrations.AddField(
            model_name='aisetting',
            name='embedding_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'model_type': 'embedding'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='embedding_settings', to='system.aimodel', verbose_name='默认Embedding模型'),
        ),
        migrations.AddField(
            model_name='aisetting',
            name='rerank_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'model_type': 'rerank'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rerank_settings', to='system.aimodel', verbose_name='默认Rerank模型'),
        ),
        migrations.AlterField(
            model_name='aisetting',
            name='ai_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_settings', to='system.aimodel', verbose_name='默认AI模型'),
        ),
        migrations.RunPython(seed_enterprise_ai_models, migrations.RunPython.noop),
    ]
