# Generated by Django 5.2.7 on 2026-06-27 05:01

import django.db.models.deletion
from django.db import migrations, models


def seed_speech_ai_models(apps, schema_editor):
    AIModel = apps.get_model('system', 'AIModel')
    defaults = [
        {
            'name': '阿里云 Paraformer Realtime',
            'model_slug': 'paraformer-realtime-v2',
            'base_url': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
            'provider': 'aliyun_dashscope',
            'model_type': 'asr',
            'description': '语音识别模型。若供应商接口不兼容 OpenAI Audio API，会明确失败并降级为手动输入。',
            'supports_json_mode': False,
        },
        {
            'name': '阿里云 CosyVoice',
            'model_slug': 'cosyvoice-v1',
            'base_url': 'https://dashscope.aliyuncs.com/compatible-mode/v1',
            'provider': 'aliyun_dashscope',
            'model_type': 'tts',
            'description': '语音合成模型。用于生成 AI 面试官问题语音，失败时前端降级浏览器 TTS。',
            'supports_json_mode': False,
        },
    ]
    for item in defaults:
        AIModel.objects.update_or_create(
            model_slug=item['model_slug'],
            defaults={**item, 'is_active': True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_aimodel_dimension_aimodel_model_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aisetting',
            name='asr_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'model_type': 'asr'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asr_settings', to='system.aimodel', verbose_name='默认ASR模型'),
        ),
        migrations.AddField(
            model_name='aisetting',
            name='tts_model',
            field=models.ForeignKey(blank=True, limit_choices_to={'model_type': 'tts'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tts_settings', to='system.aimodel', verbose_name='默认TTS模型'),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='model_type',
            field=models.CharField(choices=[('chat', '对话模型'), ('embedding', 'Embedding模型'), ('rerank', 'Rerank模型'), ('asr', '语音识别模型'), ('tts', '语音合成模型')], db_index=True, default='chat', max_length=20, verbose_name='模型类型'),
        ),
        migrations.RunPython(seed_speech_ai_models, migrations.RunPython.noop),
    ]
