# Generated by Django 5.2.7 on 2026-07-13 07:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_aisetting_asr_model_aisetting_tts_model_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('model_type', models.CharField(choices=[('chat', '对话模型'), ('embedding', 'Embedding模型'), ('rerank', 'Rerank模型'), ('asr', '语音识别模型'), ('tts', '语音合成模型')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['model_type', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ProviderCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('provider', models.CharField(db_index=True, default='openai_compatible', max_length=50)),
                ('scope', models.CharField(choices=[('platform', '平台凭据'), ('byok', '用户自带密钥')], db_index=True, default='byok', max_length=16)),
                ('encrypted_secret', models.TextField(blank=True)),
                ('secret_hint', models.CharField(blank=True, max_length=32)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credentials', to='system.aimodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='provider_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['scope', 'provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModelDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('provider', models.CharField(db_index=True, max_length=50)),
                ('remote_model', models.CharField(max_length=160)),
                ('model_type', models.CharField(choices=[('chat', '对话模型'), ('embedding', 'Embedding模型'), ('rerank', 'Rerank模型'), ('asr', '语音识别模型'), ('tts', '语音合成模型')], db_index=True, max_length=20)),
                ('base_url', models.URLField(max_length=500)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('context_window', models.PositiveIntegerField(blank=True, null=True)),
                ('input_price_per_million', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('output_price_per_million', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('timeout_seconds', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_health_status', models.CharField(blank=True, max_length=24)),
                ('last_health_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments', to='system.providercredential')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RoutePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('priority', '按优先级故障转移'), ('weighted', '加权选择')], default='priority', max_length=16)),
                ('total_timeout_seconds', models.PositiveIntegerField(default=45)),
                ('max_attempts', models.PositiveIntegerField(default=2)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alias', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_policy', to='system.modelalias')),
            ],
        ),
        migrations.CreateModel(
            name='RoutePolicyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=100)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_targets', to='system.modeldeployment')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='system.routepolicy')),
            ],
            options={
                'ordering': ['order', 'deployment__priority'],
            },
        ),
        migrations.CreateModel(
            name='UsageBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_token_limit', models.PositiveBigIntegerField(default=0, help_text='0 表示不限制')),
                ('monthly_cost_limit', models.DecimalField(decimal_places=4, default=0, help_text='0 表示不限制', max_digits=12)),
                ('period_start', models.DateField()),
                ('used_input_tokens', models.PositiveBigIntegerField(default=0)),
                ('used_output_tokens', models.PositiveBigIntegerField(default=0)),
                ('used_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='model_usage_budget', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRequestLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('task_name', models.CharField(db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('running', '运行中'), ('succeeded', '成功'), ('failed', '失败'), ('rejected', '额度拒绝')], db_index=True, default='running', max_length=16)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('fallback_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('alias', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_ledgers', to='system.modelalias')),
                ('deployment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_ledgers', to='system.modeldeployment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_request_ledgers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'task_name', 'created_at'], name='system_mode_user_id_4456f7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='providercredential',
            index=models.Index(fields=['user', 'provider', 'scope', 'is_active'], name='system_prov_user_id_b1b9d1_idx'),
        ),
        migrations.AddConstraint(
            model_name='routepolicytarget',
            constraint=models.UniqueConstraint(fields=('policy', 'deployment'), name='uniq_policy_deployment'),
        ),
    ]
