# Generated by Django 5.2.7 on 2026-07-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_seed_gateway_and_encrypt_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldeployment',
            name='tokenizer_family',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='modeldeployment',
            name='tokenizer_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
