# Generated by Django 5.2.7 on 2026-07-26 02:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_modeldeployment_tokenizer_family_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('running', '运行中'), ('succeeded', '成功'), ('failed', '失败')], db_index=True, default='running', max_length=16)),
                ('retryable', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('latency_ms', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('deployment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_attempts', to='system.modeldeployment')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='system.modelrequestledger')),
            ],
            options={
                'ordering': ['attempt_number'],
                'constraints': [models.UniqueConstraint(fields=('request', 'attempt_number'), name='uniq_model_request_attempt')],
            },
        ),
    ]
