# Generated by Django 5.2.7 on 2026-07-15 12:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsyncOperation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(db_index=True, max_length=80)),
                ('source_app', models.CharField(max_length=40)),
                ('source_model', models.CharField(max_length=80)),
                ('source_id', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', '排队中'), ('running', '处理中'), ('review_required', '待确认'), ('succeeded', '已完成'), ('failed', '失败'), ('canceled', '已取消')], db_index=True, default='pending', max_length=24)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=120)),
                ('error_message', models.TextField(blank=True)),
                ('retryable', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='async_operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'source_app', 'source_model', 'source_id'), name='uniq_async_operation_source')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(db_index=True, max_length=120)),
                ('key', models.CharField(max_length=160)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(default=200)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'scope', 'created_at'], name='core_idempo_user_id_a577f8_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'scope', 'key'), name='uniq_user_idempotency_scope_key')],
            },
        ),
    ]
