# Generated by Django 5.2.7 on 2026-07-26 02:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_idempotency_claims'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('updated_by_staff_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerInbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consumer_name', models.CharField(max_length=120)),
                ('event_id', models.UUIDField()),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('event_version', models.PositiveSmallIntegerField(default=1)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', '处理中'), ('processed', '已完成'), ('failed', '失败')], db_index=True, default='processing', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=1)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('last_error', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['consumer_name', 'status', 'created_at'], name='core_consum_consume_e3a0db_idx')],
                'constraints': [models.UniqueConstraint(fields=('consumer_name', 'event_id'), name='uniq_consumer_inbox_event')],
            },
        ),
        migrations.CreateModel(
            name='IntegrationOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('event_version', models.PositiveSmallIntegerField(default=1)),
                ('producer', models.CharField(db_index=True, max_length=64)),
                ('aggregate_type', models.CharField(max_length=80)),
                ('aggregate_id', models.CharField(db_index=True, max_length=120)),
                ('tenant_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('actor_id', models.CharField(blank=True, max_length=120)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4)),
                ('causation_id', models.UUIDField(blank=True, null=True)),
                ('trace_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('privacy_class', models.CharField(choices=[('public', '公开'), ('internal', '内部'), ('sensitive_reference', '敏感引用')], default='internal', max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', '待投递'), ('publishing', '投递中'), ('published', '已投递'), ('failed', '待重试'), ('dead', '已进入死信')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('available_at', models.DateTimeField(db_index=True)),
                ('locked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'available_at', 'created_at'], name='core_integr_status_fdf592_idx'), models.Index(fields=['producer', 'event_type', 'created_at'], name='core_integr_produce_2b5e9f_idx')],
            },
        ),
    ]
