# Generated by Django 5.2.7 on 2026-07-13 08:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_client_message_ids(apps, schema_editor):
    Message = apps.get_model('chat', 'Message')
    database = schema_editor.connection.alias
    for message_id in Message.objects.using(database).values_list('id', flat=True).iterator():
        Message.objects.using(database).filter(id=message_id).update(
            client_message_id=uuid.uuid4()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_initial'),
        ('chat', '0001_initial'),
        ('interviews', '0015_interviewsession_jd_snapshot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('topic', models.CharField(max_length=160)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', '待发布'), ('published', '已发布'), ('failed', '失败')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationParticipantState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='chat/attachments/%Y/%m/')),
                ('original_name', models.CharField(max_length=255)),
                ('mime_type', models.CharField(max_length=120)),
                ('size', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('scan_status', models.CharField(choices=[('pending', '待扫描'), ('clean', '安全'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', '待处理'), ('resolved', '已处理'), ('rejected', '已驳回')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='careers.jobapplication'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('user_dm', '用户私信'), ('application', '投递沟通'), ('interview_support', '面试支持')], db_index=True, default='user_dm', max_length=24),
        ),
        migrations.AddField(
            model_name='conversation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conversation',
            name='interview_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_conversations', to='interviews.interviewsession'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='client_message_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('delivered', '已送达'), ('read', '已读'), ('failed', '失败')], db_index=True, default='sent', max_length=16),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='chat.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_url',
            field=models.URLField(blank=True, help_text='旧版兼容 URL', max_length=512, null=True),
        ),
        migrations.RunPython(backfill_client_message_ids, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('conversation', 'sender', 'client_message_id'), name='uniq_chat_client_message'),
        ),
        migrations.AddField(
            model_name='chatoutbox',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbox_events', to='chat.message'),
        ),
        migrations.AddField(
            model_name='conversationparticipantstate',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_states', to='chat.conversation'),
        ),
        migrations.AddField(
            model_name='conversationparticipantstate',
            name='last_read_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chat.message'),
        ),
        migrations.AddField(
            model_name='conversationparticipantstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='chat.message'),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_attachments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chat.message'),
        ),
        migrations.AddField(
            model_name='messagereport',
            name='reporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userblock',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipantstate',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='uniq_conversation_participant_state'),
        ),
        migrations.AddConstraint(
            model_name='messagereport',
            constraint=models.UniqueConstraint(fields=('reporter', 'message'), name='uniq_message_report'),
        ),
        migrations.AddConstraint(
            model_name='userblock',
            constraint=models.UniqueConstraint(fields=('blocker', 'blocked'), name='uniq_user_block'),
        ),
    ]
