# Generated by Django 5.2.7 on 2026-07-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatoutbox_conversationparticipantstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageattachment',
            name='scan_detail',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='messageattachment',
            name='scan_engine',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
