# Generated by Django 5.0.3 on 2025-10-21 07:10

import templates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='模板名称')),
                ('slug', models.SlugField(help_text="模板的唯一英文标识，例如 'classic-blue'", max_length=100, unique=True, verbose_name='模板标识')),
                ('source_file', models.FileField(blank=True, help_text='上传 .docx 格式的模板文件', null=True, upload_to=templates.models.template_upload_path, verbose_name='模板源文件 (.docx)')),
                ('preview_image', models.ImageField(upload_to=templates.models.template_upload_path, verbose_name='预览图')),
                ('structure_json', models.JSONField(blank=True, default=dict, help_text='由系统自动从源文件解析生成，请勿手动修改', verbose_name='模板结构 (JSON)')),
                ('description', models.TextField(blank=True, verbose_name='模板描述')),
                ('is_public', models.BooleanField(default=False, help_text='勾选后，所有用户都可以在模板市场看到此模板', verbose_name='是否发布')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '简历模板',
                'verbose_name_plural': '简历模板',
                'ordering': ['order'],
            },
        ),
    ]
