"""
Django settings for ai_interview_backend project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
#后台管理地址：http://localhost:8000/admin/
#接口文档地址：http://127.0.0.1:8000/api/v1/schema/swagger-ui/
import os
from pathlib import Path
from corsheaders.defaults import default_headers
from dotenv import load_dotenv # 添加这一行

from .database import postgres_database_config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env')) # 添加这一行，加载 .env 文件
load_dotenv(os.path.join(BASE_DIR.parent, '.env.infra'), override=False)
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

PUBLIC_BACKEND_URL = os.getenv('PUBLIC_BACKEND_URL', 'http://127.0.0.1:8000').rstrip('/')
PUBLIC_FRONTEND_URL = os.getenv('PUBLIC_FRONTEND_URL', 'http://127.0.0.1:5173').rstrip('/')
PUBLIC_ADMIN_URL = os.getenv('PUBLIC_ADMIN_URL', 'http://127.0.0.1:5174').rstrip('/')
GITHUB_CLIENT_ID = os.getenv('GITHUB_CLIENT_ID', '')
GITHUB_CLIENT_SECRET = os.getenv('GITHUB_CLIENT_SECRET', '')
GITHUB_OAUTH_CALLBACK_URL = os.getenv(
    'GITHUB_OAUTH_CALLBACK_URL',
    f'{PUBLIC_BACKEND_URL}/api/v1/auth/oauth/github/callback/',
)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'simpleui',  # 【核心新增】将 simpleui 放在第一行
    'drf_spectacular',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'corsheaders',
    # 3rd party apps
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',
    'django.contrib.sites',  # allauth 需要这个
    'allauth',  # allauth 核心
    'allauth.account',  # allauth 账户管理
    'allauth.mfa',
    'allauth.socialaccount',  # allauth 第三方账户
    'allauth.socialaccount.providers.github',  # GitHub 提供商
    'dj_rest_auth',  # 新增
    'dj_rest_auth.registration',  # 新增
    'django_filters',
    # Local apps
    'users',
    'careers',
    'resumes',
    'interviews',
    'reports',
    'questions',
    'system',
    'blog',
    'community',
    'interactions',
    'notifications',
   'chat',
   'video_uploads',
    'knowledge',
   'staff_admin',
]

# 3. 将应用的入口指向 Channels 的 ASGI application
ASGI_APPLICATION = 'ai_interview_backend.asgi.application'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'core.middleware.RequestIdMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 【核心修正】添加 allauth 的中间件
    # 官方建议将它放在 AuthenticationMiddleware 之后
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'ai_interview_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_interview_backend.wsgi.application'


# PostgreSQL is the only relational runtime database.
default_database_url = (
    f"postgresql://{os.getenv('POSTGRES_USER', 'ifaceoff_app')}:"
    f"{os.getenv('POSTGRES_PASSWORD', 'ifaceoff-app-change-me')}@"
    f"{os.getenv('POSTGRES_HOST', '127.0.0.1')}:"
    f"{os.getenv('POSTGRES_PORT', '5433')}/"
    f"{os.getenv('POSTGRES_DB', 'ifaceoff_app')}"
)
DATABASES = {
    'default': postgres_database_config(
        os.getenv('IFACEOFF_DATABASE_URL', default_database_url),
        conn_max_age=int(os.getenv('POSTGRES_CONN_MAX_AGE', '0')),
        pool_enabled=os.getenv('POSTGRES_POOL_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on'),
        disable_server_side_cursors=os.getenv('POSTGRES_DISABLE_SERVER_SIDE_CURSORS', 'true').lower()
        in ('1', 'true', 'yes', 'on'),
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# 【核心新增】The absolute path to the directory where collectstatic will collect static files for deployment.
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# 指定自定义的用户模型
AUTH_USER_MODEL = 'users.User'


# Django REST Framework 配置
REST_FRAMEWORK = {
    # 默认的权限策略：除非明确指定，否则所有接口都需要认证
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # 默认的认证方案：使用 JWT
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',
        'user': '300/min',
        'login': '5/min',
        'verification': '5/min',
        'chat': '60/min',
        'upload': '10/min',
        'ai_action': '20/hour',
    },
    'EXCEPTION_HANDLER': 'core.exceptions.api_exception_handler',
    #添加这一行来全局启用分页
    'DEFAULT_PAGINATION_CLASS': 'core.pagination.StandardResultsSetPagination',
# 【核心新增】告诉 DRF 使用 spectacular 来生成 API schema
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Simple JWT 配置
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=2),    # Access Token 有效期
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),     # Refresh Token 有效期
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True, # 登录后更新 last_login 字段

    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY, # 使用 Django 的 SECRET_KEY
    "VERIFYING_KEY": "",
    "AUDIENCE": None,
    "ISSUER": None,
    "JSON_ENCODER": None,
    "JWK_URL": None,
    "LEEWAY": 0,

    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",

    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_TYPE_CLAIM": "token_type",
    "TOKEN_USER_CLASS": "rest_framework_simplejwt.models.TokenUser",

    "JTI_CLAIM": "jti",

    "SLIDING_TOKEN_REFRESH_EXP_CLAIM": "refresh_exp",
    "SLIDING_TOKEN_LIFETIME": timedelta(minutes=5),
    "SLIDING_TOKEN_REFRESH_LIFETIME": timedelta(days=1),

    # 自定义 Token Claims，如果需要的话
    # 'TOKEN_OBTAIN_SERIALIZER': 'path.to.MyTokenObtainPairSerializer',
}

# CORS 配置
# --- CORS CONFIGURATION (Final Version) ---
#
# 允许所有来源（开发时方便，生产环境请使用下面的白名单）
CORS_ALLOW_ALL_ORIGINS = False  # 生产环境绝不能允许所有
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = (
    *default_headers,
    'idempotency-key',
    'x-auth-mode',
    'x-request-id',
)
CORS_EXPOSE_HEADERS = ('X-Request-Id', 'X-Agent-Run-Id')
CORS_ALLOWED_ORIGINS = [origin.strip() for origin in os.getenv('CORS_ALLOWED_ORIGINS', '').split(',') if origin.strip()]
if DEBUG:
    CORS_ALLOWED_ORIGINS += [
        origin for origin in [
            'http://localhost:5173',
            'http://127.0.0.1:5173',
            'http://localhost:5174',
            'http://127.0.0.1:5174',
        ]
        if origin not in CORS_ALLOWED_ORIGINS
    ]
# 确保 CSRF 信任我们的前端来源
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS
CSRF_COOKIE_NAME = 'csrftoken'
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = os.getenv('AUTH_COOKIE_SECURE', str(not DEBUG)).lower() in ('true', '1', 't')
CSRF_COOKIE_SAMESITE = os.getenv('AUTH_COOKIE_SAMESITE', 'Lax')
SESSION_COOKIE_SECURE = CSRF_COOKIE_SECURE
SESSION_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE
AUTH_REFRESH_COOKIE_NAME = os.getenv('AUTH_REFRESH_COOKIE_NAME', 'ifaceoff_refresh')
AUTH_REFRESH_COOKIE_PATH = '/api/v1/auth/'
AUTH_REFRESH_COOKIE_MAX_AGE = int(os.getenv('AUTH_REFRESH_COOKIE_MAX_AGE', 7 * 24 * 3600))
AUTH_COOKIE_SECURE = CSRF_COOKIE_SECURE
AUTH_COOKIE_SAMESITE = CSRF_COOKIE_SAMESITE
AUTH_COOKIE_DOMAIN = os.getenv('AUTH_COOKIE_DOMAIN', '') or None
KNOWLEDGE_IMPORT_MAX_FILES = int(os.getenv('KNOWLEDGE_IMPORT_MAX_FILES', '20'))
KNOWLEDGE_IMPORT_MAX_FILE_BYTES = int(os.getenv('KNOWLEDGE_IMPORT_MAX_FILE_BYTES', str(50 * 1024 * 1024)))
KNOWLEDGE_IMPORT_MAX_BATCH_BYTES = int(os.getenv('KNOWLEDGE_IMPORT_MAX_BATCH_BYTES', str(200 * 1024 * 1024)))
WS_TICKET_TTL_SECONDS = int(os.getenv('WS_TICKET_TTL_SECONDS', '45'))
WS_ALLOW_LEGACY_QUERY_JWT = os.getenv('WS_ALLOW_LEGACY_QUERY_JWT', 'False').lower() in ('true', '1', 't')
STAFF_SESSION_COOKIE_NAME = os.getenv('STAFF_SESSION_COOKIE_NAME', 'ifaceoff_staff_session')
STAFF_SESSION_HOURS = int(os.getenv('STAFF_SESSION_HOURS', '8'))
STAFF_COOKIE_DOMAIN = os.getenv('STAFF_COOKIE_DOMAIN', '') or None
# 或者使用更安全的白名单模式
# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
# ]

# # 确保 CSRF 信任我们的前端来源
# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:5173',
#     'http://127.0.0.1:5173',
# ]


# ---------------- MEDIA FILES CONFIGURATION ----------------
#
# MEDIA_URL: 访问上传文件的 URL 前缀 (必须以斜杠结尾)
# 例如: http://localhost:8000/media/resumes/my_resume.pdf
MEDIA_URL = '/media/'

# MEDIA_ROOT: 上传文件在服务器上存储的物理根目录
# os.path.join(BASE_DIR, 'media') 会在你的项目根目录下创建一个名为 'media' 的文件夹
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# ---------------- CACHES CONFIGURATION ----------------
REDIS_HOST = os.getenv('REDIS_HOST', '127.0.0.1')
REDIS_PORT = os.getenv('REDIS_PORT', '6379')
REDIS_CACHE_URL = os.getenv('REDIS_CACHE_URL', f'redis://{REDIS_HOST}:{REDIS_PORT}/1')
REDIS_REALTIME_URL = os.getenv('REDIS_REALTIME_URL', f'redis://{REDIS_HOST}:{REDIS_PORT}/3')


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_CACHE_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        },
        "TIMEOUT": 3600,
        "KEY_PREFIX": "ifaceoff-cache",
    },
    "realtime": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_REALTIME_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": False,
        },
        "TIMEOUT": 300,
        "KEY_PREFIX": "ifaceoff-realtime",
    },
}

# --- EMAIL SETTINGS ---
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 't')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1', 't')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# 默认发件人地址
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# --- ALLAUTH CONFIGURATION (Final SPA Version) ---
AUTH_USER_MODEL = 'users.User'
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]
SITE_ID = 1
# 【核心修正】指定使用我们自定义的 SocialAccountAdapter
SOCIALACCOUNT_ADAPTER = 'users.adapter.CustomSocialAccountAdapter'
ACCOUNT_ADAPTER = 'allauth.account.adapter.DefaultAccountAdapter'
ACCOUNT_LOGIN_METHODS = {"email"}
ACCOUNT_SIGNUP_FIELDS = ["email*", "password1*", "password2*"]
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_EMAIL_VERIFICATION = "none"
SOCIALACCOUNT_LOGIN_ON_GET = True

SOCIALACCOUNT_PROVIDERS = {
    'github': { 'SCOPE': [ 'user:email' ] }
}

# --- DJ-REST-AUTH CONFIGURATION (保持不变) ---
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,
    'TOKEN_MODEL': None,
}

# --- CELERY SETTINGS ---
# 指定消息中间件(Broker)的地址，我们使用 Redis 的 2 号数据库
# # 避免与缓存使用的 1 号数据库冲突
# CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2'
# 添加 RabbitMQ 的配置
# amqp://guest:guest@localhost:5672// 是 RabbitMQ 的默认连接地址

RABBITMQ_HOST = os.getenv('RABBITMQ_HOST', 'localhost')

CELERY_BROKER_URL = f'amqp://guest:guest@{RABBITMQ_HOST}:5672//'
# 指定结果后端(Result Backend)的地址，用于存储任务执行结果
# Celery results are an operational acceleration layer. Durable task state lives
# in PostgreSQL, so production may safely place these keys in the evictable
# cache Redis without coupling workers to the realtime Redis fault domain.
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', REDIS_CACHE_URL)
# 接受的内容类型
CELERY_ACCEPT_CONTENT = ['json']
# 任务序列化方式
CELERY_TASK_SERIALIZER = 'json'
# 结果序列化方式
CELERY_RESULT_SERIALIZER = 'json'
# Celery 使用的时区
CELERY_TIMEZONE = 'UTC' # 与 Django 的 TIME_ZONE 保持一致
CELERY_WORKER_PREFETCH_MULTIPLIER = int(os.getenv('CELERY_WORKER_PREFETCH_MULTIPLIER', '1'))
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_TRACK_STARTED = True
CELERY_INSPECT_TIMEOUT_SECONDS = float(os.getenv('CELERY_INSPECT_TIMEOUT_SECONDS', '2'))
CELERY_TASK_ROUTES = {
    'interviews.tasks.run_interview_execution': {'queue': 'agent'},
    'interviews.tasks.run_composite_v4_turn': {'queue': 'agent'},
    'knowledge.tasks.*': {'queue': 'documents'},
    'resumes.tasks.*': {'queue': 'documents'},
    'video_uploads.tasks.*': {'queue': 'media'},
    'notifications.tasks.*': {'queue': 'notifications'},
    'chat.tasks.*': {'queue': 'notifications'},
}

# --- CELERY BEAT SETTINGS (定时任务调度器) ---
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    # 任务名称，可以任意取
    'cleanup-stale-interviews-every-30-minutes': {
        # 指向我们刚刚创建的任务，格式为: 'app_name.tasks.task_function_name'
        'task': 'interviews.tasks.cleanup_stale_interviews',
        # 'schedule': crontab(minute='*/30'), # 每30分钟执行一次
        'schedule': 900, # 为简单起见，我们也可以设置为每 900秒执行一次
    },
    'record-daily-post-stats-nightly': {
        'task': 'blog.tasks.record_daily_stats',
        'schedule': crontab(hour=23, minute=50),  # 每天晚上 23:50 执行
    },
    'publish-chat-outbox-every-minute': {
        'task': 'chat.tasks.publish_pending_chat_outbox',
        'schedule': 60,
    },
    'publish-notification-outbox-every-minute': {
        'task': 'notifications.tasks.publish_notification_outbox',
        'schedule': 60,
    },
    'mark-stale-resume-imports': {
        'task': 'resumes.tasks.mark_stale_resume_import_jobs',
        'schedule': 300,
    },
    'mark-stale-knowledge-jobs': {
        'task': 'knowledge.tasks.mark_stale_knowledge_jobs',
        'schedule': 300,
    },
    'publish-agent-dispatch-outbox': {
        'task': 'interviews.tasks.publish_pending_agent_dispatches',
        'schedule': 2,
        'options': {'queue': 'notifications'},
    },
    'recover-stale-agent-executions': {
        'task': 'interviews.tasks.recover_stale_agent_executions',
        'schedule': 60,
        'options': {'queue': 'notifications'},
    },
}
#celery -A ai_interview_backend worker -l info -P gevent
# celery -A ai_interview_backend beat -l info

# 4. 配置 Channel Layer，使用 Redis
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            # 【核心修改】使用 redis://host:port/db 的格式
            # 注意：这里假设您的 REDIS_HOST 和 REDIS_PORT 变量已经定义好了
            "hosts": [REDIS_REALTIME_URL],
        },
    },
}

# --- INTERVIEW AGENT / RAG SETTINGS ---
INTERVIEW_AGENT_ENGINE = os.getenv('INTERVIEW_AGENT_ENGINE', 'composite_v4')
AGENT_DATABASE_URL = os.getenv('AGENT_DATABASE_URL', '')
LITELLM_DATABASE_URL = os.getenv('LITELLM_DATABASE_URL', '')
LANGFUSE_DATABASE_URL = os.getenv('LANGFUSE_DATABASE_URL', '')
AGENT_V3_DEFAULT_TARGET_DURATION_MINUTES = int(os.getenv('AGENT_V3_DEFAULT_TARGET_DURATION_MINUTES', '30'))
AGENT_V3_DEFAULT_MIN_DURATION_MINUTES = int(os.getenv('AGENT_V3_DEFAULT_MIN_DURATION_MINUTES', '20'))
AGENT_V3_DEFAULT_HARD_MAX_DURATION_MINUTES = int(os.getenv('AGENT_V3_DEFAULT_HARD_MAX_DURATION_MINUTES', '45'))
INTERVIEW_GENERATION_JOB_STALE_SECONDS = int(os.getenv('INTERVIEW_GENERATION_JOB_STALE_SECONDS', '90'))
AGENT_TOOL_TIMEOUT_SECONDS = int(os.getenv('AGENT_TOOL_TIMEOUT_SECONDS', '30'))
AGENT_CONTEXT_TOKEN_BUDGET = int(os.getenv('AGENT_CONTEXT_TOKEN_BUDGET', '6000'))
AGENT_ENABLE_SLASH_COMMANDS = os.getenv('AGENT_ENABLE_SLASH_COMMANDS', 'true').lower() in ('1', 'true', 'yes', 'on')
AGENT_ENABLE_MCP_ADAPTER = os.getenv('AGENT_ENABLE_MCP_ADAPTER', 'false').lower() in ('1', 'true', 'yes', 'on')
AGENT_PROMPT_VERSION = os.getenv('AGENT_PROMPT_VERSION', 'interview-agent-v1')
AGENT_STATE_SCHEMA_VERSION = int(os.getenv('AGENT_STATE_SCHEMA_VERSION', '4'))
AGENT_MEMORY_EVENT_RETENTION_DAYS = int(os.getenv('AGENT_MEMORY_EVENT_RETENTION_DAYS', '30'))
AGENT_CHECKPOINT_RETENTION_DAYS = int(os.getenv('AGENT_CHECKPOINT_RETENTION_DAYS', '30'))
AGENT_MAX_GENERATION_RETRIES = int(os.getenv('AGENT_MAX_GENERATION_RETRIES', '2'))
AGENT_EVALUATION_CONFIDENCE_THRESHOLD = float(os.getenv('AGENT_EVALUATION_CONFIDENCE_THRESHOLD', '0.6'))
AGENT_NODE_TIMEOUT_SECONDS = int(os.getenv('AGENT_NODE_TIMEOUT_SECONDS', '30'))
AGENT_EVENT_STREAM_MAXLEN = int(os.getenv('AGENT_EVENT_STREAM_MAXLEN', '2000'))
INTERVIEW_LOCK_TIMEOUT_MS = int(os.getenv('INTERVIEW_LOCK_TIMEOUT_MS', '1500'))
AGENT_EXECUTION_STALE_SECONDS = int(os.getenv('AGENT_EXECUTION_STALE_SECONDS', '360'))
AGENT_EVENT_STREAM_TTL_SECONDS = int(os.getenv('AGENT_EVENT_STREAM_TTL_SECONDS', '86400'))
MODEL_GATEWAY_TIMEOUT_SECONDS = int(os.getenv('MODEL_GATEWAY_TIMEOUT_SECONDS', '30'))
MODEL_CREDENTIAL_ENCRYPTION_KEY = os.getenv('MODEL_CREDENTIAL_ENCRYPTION_KEY', '')
LITELLM_PROXY_URL = os.getenv('LITELLM_PROXY_URL', 'http://127.0.0.1:4000/v1')
LANGFUSE_ENABLED = os.getenv('LANGFUSE_ENABLED', 'false').lower() in ('1', 'true', 'yes', 'on')
RESUME_UPLOAD_MAX_BYTES = int(os.getenv('RESUME_UPLOAD_MAX_BYTES', str(15 * 1024 * 1024)))
DISCOURSE_BASE_URL = os.getenv('DISCOURSE_BASE_URL', '')
DISCOURSE_CONNECT_SECRET = os.getenv('DISCOURSE_CONNECT_SECRET', '')
DISCOURSE_WEBHOOK_SECRET = os.getenv('DISCOURSE_WEBHOOK_SECRET', '')
MEILISEARCH_URL = os.getenv('MEILISEARCH_URL', 'http://127.0.0.1:7700')
MEILISEARCH_API_KEY = os.getenv('MEILISEARCH_API_KEY', os.getenv('MEILI_MASTER_KEY', ''))
MEILISEARCH_KNOWLEDGE_INDEX = os.getenv('MEILISEARCH_KNOWLEDGE_INDEX', 'interview_knowledge_chunks')
CLAMAV_HOST = os.getenv('CLAMAV_HOST', '127.0.0.1')
CLAMAV_PORT = int(os.getenv('CLAMAV_PORT', '3310'))
CLAMAV_REQUIRED = os.getenv('CLAMAV_REQUIRED', 'false').lower() in ('1', 'true', 'yes', 'on')
QDRANT_URL = os.getenv('QDRANT_URL', f"http://127.0.0.1:{os.getenv('QDRANT_PORT', '6333')}")
QDRANT_COLLECTION = os.getenv('QDRANT_COLLECTION', 'interview_knowledge')
EMBEDDING_MODEL = os.getenv('EMBEDDING_MODEL', 'text-embedding-3-small')
EMBEDDING_API_KEY = os.getenv('EMBEDDING_API_KEY', '')
EMBEDDING_BASE_URL = os.getenv('EMBEDDING_BASE_URL', '')
DOCUMENT_PARSER = os.getenv('DOCUMENT_PARSER', 'docling')
DOCLING_ENABLE_OCR = os.getenv('DOCLING_ENABLE_OCR', 'true').lower() in ('1', 'true', 'yes', 'on')
DOCLING_ENABLE_TABLE_STRUCTURE = os.getenv('DOCLING_ENABLE_TABLE_STRUCTURE', 'true').lower() in ('1', 'true', 'yes', 'on')
OCR_ENGINE = os.getenv('OCR_ENGINE', 'paddleocr')
PADDLEOCR_LANG = os.getenv('PADDLEOCR_LANG', 'ch')
HYBRID_SEARCH_TOPN = int(os.getenv('HYBRID_SEARCH_TOPN', '30'))
HYBRID_SEARCH_TOPK = int(os.getenv('HYBRID_SEARCH_TOPK', '4'))
HYBRID_SEARCH_PARALLELISM = int(os.getenv('HYBRID_SEARCH_PARALLELISM', '4'))
ASR_CHUNK_SECONDS = int(os.getenv('ASR_CHUNK_SECONDS', '2'))
ASR_MIN_CONFIDENCE = float(os.getenv('ASR_MIN_CONFIDENCE', '0.65'))
SPEECH_MAX_AUDIO_BYTES = int(os.getenv('SPEECH_MAX_AUDIO_BYTES', str(25 * 1024 * 1024)))
TTS_CACHE_SECONDS = int(os.getenv('TTS_CACHE_SECONDS', '86400'))
SPEECH_PROVIDER_TIMEOUT_SECONDS = int(os.getenv('SPEECH_PROVIDER_TIMEOUT_SECONDS', '30'))
TTS_DEFAULT_VOICE = os.getenv('TTS_DEFAULT_VOICE', 'alloy')
TTS_RESPONSE_FORMAT = os.getenv('TTS_RESPONSE_FORMAT', 'mp3')
