# Generated by Django 5.0.3 on 2025-10-29 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='是否已读')),
                ('verb', models.CharField(choices=[('commented', '评论了你的文章'), ('replied', '回复了你的评论'), ('liked_post', '点赞了你的文章'), ('bookmarked_post', '收藏了你的文章'), ('followed', '关注了你'), ('mentioned', '在评论中提到了你'), ('new_post', '发布了新文章'), ('interview_report_ready', '面试报告已生成'), ('resume_analysis_ready', '简历分析报告已生成')], max_length=50, verbose_name='通知类型')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_object_id', models.CharField(max_length=255)),
                ('target_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_object_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_object_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_action_objects', to='contenttypes.contenttype')),
                ('actor_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_actors', to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='接收者')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_targets', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ['-timestamp'],
            },
        ),
    ]
