# Generated by Django 5.2.7 on 2025-11-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPostStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='日期')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='当日浏览量')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='当日点赞量')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='blog.post')),
            ],
            options={
                'verbose_name': '文章每日统计',
                'verbose_name_plural': '文章每日统计',
                'unique_together': {('post', 'date')},
            },
        ),
    ]
