# Generated by Django 5.2.7 on 2025-11-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_dailypoststats'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='bookmark_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='收藏数'),
        ),
    ]
