# Generated by Django 5.0.3 on 2025-11-09 19:30

from django.db import migrations
from django.db.models import Count


def backfill_counts(apps, schema_editor):
    """
    遍历所有 Post，回填正确的 like_count, bookmark_count, 和 comment_count。
    """
    Post = apps.get_model('blog', 'Post')
    Like = apps.get_model('interactions', 'Like')
    Bookmark = apps.get_model('interactions', 'Bookmark')
    Comment = apps.get_model('blog', 'Comment')

    for post in Post.objects.all():
        # 计算每篇文章的点赞、收藏、评论总数
        likes_count = Like.objects.filter(post=post).count()
        bookmarks_count = Bookmark.objects.filter(post=post).count()
        comments_count = Comment.objects.filter(post=post).count()

        # 更新 Post 实例
        post.like_count = likes_count
        post.bookmark_count = bookmarks_count
        post.comment_count = comments_count

        # 只保存，不触发信号，避免重复计数
        post.save(update_fields=['like_count', 'bookmark_count', 'comment_count'])


def reverse_code(apps, schema_editor):
    """
    反向操作，如果需要的话可以什么都不做。
    """
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0004_post_bookmark_count'),  # 请确保这里的 '0002_auto_...' 是您上一个 blog 迁移文件的名字
        ('interactions', '0001_initial'),  # 确保依赖 interactions 应用的初始迁移
    ]

    operations = [
        migrations.RunPython(backfill_counts, reverse_code),
    ]