# Generated by Django 5.0.3 on 2025-10-19 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resumes', '0005_resume_template_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysisReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jd_text', models.TextField(verbose_name='目标岗位JD')),
                ('report_data', models.JSONField(verbose_name='AI分析报告JSON')),
                ('overall_score', models.IntegerField(default=0, verbose_name='综合匹配度得分')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '简历分析报告',
                'verbose_name_plural': '简历分析报告',
                'ordering': ['-created_at'],
            },
        ),
    ]
