# Generated by Django 5.2.7 on 2026-07-13 12:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_initial'),
        ('reports', '0001_initial'),
        ('resumes', '0007_backfill_resume_versions'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeanalysisreport',
            name='evidence_sources',
            field=models.JSONField(blank=True, default=list, verbose_name='证据来源'),
        ),
        migrations.AddField(
            model_name='resumeanalysisreport',
            name='job_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_analysis_reports', to='careers.jobtarget', verbose_name='目标岗位来源'),
        ),
        migrations.AddField(
            model_name='resumeanalysisreport',
            name='model_config_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='模型配置快照'),
        ),
        migrations.AddField(
            model_name='resumeanalysisreport',
            name='resume_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='简历版本快照'),
        ),
        migrations.AddField(
            model_name='resumeanalysisreport',
            name='resume_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analysis_reports', to='resumes.resumeversion', verbose_name='简历版本快照来源'),
        ),
    ]
