# Generated by Django 5.0.3 on 2025-09-18 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='简历标题')),
                ('file_url', models.CharField(max_length=255, verbose_name='文件存储 URL')),
                ('file_type', models.CharField(max_length=20, verbose_name='文件类型')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='文件大小 (KB)')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认简历')),
                ('status', models.CharField(choices=[('pending', '待解析'), ('parsed', '已解析'), ('failed', '解析失败')], default='pending', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('parsed_content', models.TextField(blank=True, verbose_name='解析后的文本内容')),
                ('optimization_suggestions', models.TextField(blank=True, verbose_name='优化建议')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'ordering': ['-created_at'],
            },
        ),
    ]
