# Generated by Django 5.0.3 on 2025-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=100, verbose_name='学校名称')),
                ('degree', models.CharField(max_length=50, verbose_name='学位')),
                ('major', models.CharField(max_length=100, verbose_name='专业')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
            ],
            options={
                'verbose_name': '教育经历',
                'verbose_name_plural': '教育经历',
                'ordering': ['-end_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('role', models.CharField(max_length=100, verbose_name='担任角色')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(verbose_name='项目描述')),
            ],
            options={
                'verbose_name': '项目经历',
                'verbose_name_plural': '项目经历',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='简历标题')),
                ('file', models.FileField(blank=True, null=True, upload_to='resumes/', verbose_name='上传的简历文件')),
                ('parsed_content', models.TextField(blank=True, verbose_name='解析后的文本内容')),
                ('full_name', models.CharField(blank=True, max_length=100, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='电话')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='期望职位')),
                ('city', models.CharField(blank=True, max_length=50, verbose_name='城市')),
                ('summary', models.TextField(blank=True, verbose_name='个人总结')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认简历')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('parsed', '（文件）已解析'), ('failed', '（文件）解析失败')], default='draft', max_length=20, verbose_name='状态')),
                ('optimization_suggestions', models.JSONField(blank=True, null=True, verbose_name='优化建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, verbose_name='技能名称')),
                ('proficiency', models.CharField(blank=True, max_length=50, verbose_name='熟练度')),
            ],
            options={
                'verbose_name': '专业技能',
                'verbose_name_plural': '专业技能',
            },
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100, verbose_name='公司名称')),
                ('position', models.CharField(max_length=100, verbose_name='职位')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('description', models.TextField(verbose_name='工作描述')),
            ],
            options={
                'verbose_name': '工作经历',
                'verbose_name_plural': '工作经历',
                'ordering': ['-start_date'],
            },
        ),
    ]
