# Generated by Django 5.0.3 on 2025-09-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='file_url',
        ),
        migrations.AddField(
            model_name='resume',
            name='file',
            field=models.FileField(default='no-file.pdf', upload_to='resumes/', verbose_name='简历文件'),
            preserve_default=False,
        ),
    ]
