# Generated by Django 5.0.3 on 2025-10-12 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='city',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='email',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='summary',
        ),
        migrations.AddField(
            model_name='resume',
            name='content_json',
            field=models.JSONField(blank=True, null=True, verbose_name='在线简历JSON内容'),
        ),
    ]
