# Generated by Django 5.0.3 on 2025-10-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0003_remove_resume_city_remove_resume_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='城市'),
        ),
        migrations.AddField(
            model_name='resume',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='resume',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='期望职位'),
        ),
        migrations.AddField(
            model_name='resume',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='电话'),
        ),
        migrations.AddField(
            model_name='resume',
            name='summary',
            field=models.TextField(blank=True, verbose_name='个人总结'),
        ),
    ]
