# Generated by Django 5.0.3 on 2025-10-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_resume_city_resume_email_resume_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='template_name',
            field=models.CharField(blank=True, default='default', max_length=50, verbose_name='模板名称'),
        ),
    ]
