# Generated by Django 5.2.7 on 2026-07-13 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
        ('resumes', '0005_resume_template_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-end_date']},
        ),
        migrations.AlterModelOptions(
            name='projectexperience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='resume',
            name='canonical_schema_version',
            field=models.CharField(default='1.0.0', max_length=20, verbose_name='JSON Resume 版本'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='content_json',
            field=models.JSONField(blank=True, null=True, verbose_name='旧版编辑器 JSON'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/%Y/%m/', verbose_name='上传的简历文件'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='optimization_suggestions',
            field=models.JSONField(blank=True, null=True, verbose_name='旧版优化建议'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('processing', '解析中'), ('published', '已发布'), ('parsed', '已解析'), ('failed', '解析失败')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ResumeImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待解析'), ('processing', '解析中'), ('review_required', '等待人工确认'), ('confirmed', '已确认'), ('failed', '解析失败'), ('canceled', '已取消')], db_index=True, default='pending', max_length=24)),
                ('parser_name', models.CharField(blank=True, max_length=80)),
                ('parser_version', models.CharField(blank=True, max_length=40)),
                ('parser_fallback_reason', models.TextField(blank=True)),
                ('parsed_text', models.TextField(blank=True)),
                ('parsed_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('schema_version', models.CharField(default='1.0.0', max_length=20)),
                ('resume_json', models.JSONField(default=dict, verbose_name='标准简历 JSON')),
                ('layout_json', models.JSONField(blank=True, default=dict, verbose_name='iFaceoff 布局 JSON')),
                ('evidence_snapshot', models.JSONField(blank=True, default=list, verbose_name='职业事实证据快照')),
                ('source', models.CharField(choices=[('legacy_migration', '旧数据迁移'), ('editor', '在线编辑'), ('import', '文件导入'), ('ai_suggestion', 'AI 建议'), ('jd_variant', 'JD 定制'), ('restore', '版本恢复')], default='editor', max_length=32)),
                ('change_summary', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_versions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resumes.resumeversion')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='resumes.resume')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='ResumeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job_target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_variants', to='careers.jobtarget')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_variants', to=settings.AUTH_USER_MODEL)),
                ('source_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='resumes.resumeversion')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variant_outputs', to='resumes.resumeversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch', models.JSONField(default=list, verbose_name='JSON Patch')),
                ('summary', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('evidence_fact_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('accepted', '已采纳'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_suggestions', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='resumes.resume')),
                ('accepted_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resumeversion')),
                ('base_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='resumes.resumeversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resumeversion', verbose_name='当前版本'),
        ),
        migrations.AddConstraint(
            model_name='resumeversion',
            constraint=models.UniqueConstraint(fields=('resume', 'version_number'), name='uniq_resume_version_number'),
        ),
    ]
