# Generated by Django 5.2.7 on 2026-07-26 07:40

import django.db.models.deletion
import hashlib
import json
import uuid
from django.conf import settings
from django.db import migrations, models


def _stable_hash(value):
    raw = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(',', ':'), default=str)
    return hashlib.sha256(raw.encode('utf-8')).hexdigest()


def backfill_resume_intelligence(apps, schema_editor):
    Resume = apps.get_model('resumes', 'Resume')
    ResumeVersion = apps.get_model('resumes', 'ResumeVersion')
    ResumeDraft = apps.get_model('resumes', 'ResumeDraft')
    ResumeDesignRevision = apps.get_model('resumes', 'ResumeDesignRevision')
    ResumeAsset = apps.get_model('resumes', 'ResumeAsset')
    db = schema_editor.connection.alias

    # Resolve historical duplicate defaults before the partial unique
    # constraint is installed. Keep the most recently updated resume.
    seen_users = set()
    default_rows = Resume.objects.using(db).filter(is_default=True).order_by('user_id', '-updated_at', '-pk')
    for row in default_rows.iterator():
        if row.user_id in seen_users:
            Resume.objects.using(db).filter(pk=row.pk).update(is_default=False)
        else:
            seen_users.add(row.user_id)

    template_map = {
        'default': 'ats-classic',
        'classic': 'ats-classic',
        'modern': 'modern-professional',
        'tech': 'engineering',
        'campus': 'graduate',
        'consulting': 'management-consulting',
        'academic': 'academic-research',
    }
    for resume in Resume.objects.using(db).select_related('current_version').iterator():
        version = resume.current_version
        if not version:
            version = ResumeVersion.objects.using(db).filter(resume_id=resume.pk).order_by('-version_number').first()
        if not version:
            continue
        payload = version.resume_json if isinstance(version.resume_json, dict) else {}
        payload.setdefault('basics', {})
        for section in (
            'work', 'volunteer', 'education', 'awards', 'certificates', 'publications',
            'skills', 'languages', 'interests', 'references', 'projects',
        ):
            items = payload.get(section)
            payload[section] = items if isinstance(items, list) else []
            for item in payload[section]:
                if isinstance(item, dict):
                    extension = item.setdefault('x-ifaceoff', {})
                    if isinstance(extension, dict):
                        extension.setdefault('id', str(uuid.uuid4()))
        payload.setdefault('meta', {})
        payload['meta']['schemaVersion'] = '1.3.1'
        payload.setdefault('x-ifaceoff', {})
        content_hash = _stable_hash(payload)
        ResumeVersion.objects.using(db).filter(pk=version.pk).update(
            resume_json=payload,
            schema_version='1.3.1',
            content_hash=content_hash,
            language='zh-CN',
        )
        design = {
            'template_key': template_map.get(resume.template_name, 'ats-classic'),
            'template_version': '1.0.0',
            'page_size': 'A4',
            'language': 'zh-CN',
            'font': 'Noto Sans CJK SC',
            'color': '#1F2937',
            'density': 'balanced',
            'date_format': 'YYYY-MM',
            'show_avatar': False,
            'section_order': [
                'basics', 'summary', 'work', 'projects', 'education', 'skills',
                'certificates', 'awards', 'publications', 'languages', 'volunteer', 'interests',
            ],
        }
        design_revision, _ = ResumeDesignRevision.objects.using(db).get_or_create(
            resume_id=resume.pk,
            revision_number=1,
            defaults={
                'template_key': design['template_key'],
                'template_version': '1.0.0',
                'language': 'zh-CN',
                'page_size': 'A4',
                'design_json': design,
                'design_hash': _stable_hash(design),
                'created_by_id': resume.user_id,
            },
        )
        Resume.objects.using(db).filter(pk=resume.pk).update(
            current_design_revision_id=design_revision.pk,
            canonical_schema_version='1.3.1',
        )
        etag = _stable_hash({'resume_json': payload, 'design_json': design, 'revision': 1})
        ResumeDraft.objects.using(db).get_or_create(
            resume_id=resume.pk,
            defaults={
                'base_version_id': version.pk,
                'resume_json': payload,
                'design_json': design,
                'revision': 1,
                'etag': etag,
                'updated_by_id': resume.user_id,
            },
        )
        if resume.file:
            checksum = ''
            metadata = {'legacy_file_pointer': str(resume.file)}
            try:
                with resume.file.storage.open(resume.file.name, 'rb') as source:
                    digest = hashlib.sha256()
                    for chunk in iter(lambda: source.read(1024 * 1024), b''):
                        digest.update(chunk)
                    checksum = digest.hexdigest()
            except Exception:
                checksum = hashlib.sha256(str(resume.file).encode('utf-8')).hexdigest()
                metadata['checksum_pending'] = True
            ResumeAsset.objects.using(db).get_or_create(
                resume_id=resume.pk,
                kind='source',
                file=str(resume.file),
                defaults={
                    'original_name': str(resume.file).rsplit('/', 1)[-1],
                    'size_bytes': 0,
                    'checksum_sha256': checksum,
                    'metadata': metadata,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_skilltaxonomy_jobtarget_jd_snapshot_hash_and_more'),
        ('resumes', '0007_backfill_resume_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_json', models.JSONField(default=dict)),
                ('design_json', models.JSONField(blank=True, default=dict)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('etag', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeEvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_pointer', models.CharField(max_length=500)),
                ('fact_snapshot', models.JSONField(default=dict)),
                ('fact_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['json_pointer', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ResumeQualityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '等待评审'), ('processing', '评审中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=16)),
                ('schema_version', models.CharField(default='1.3.1', max_length=20)),
                ('config_hash', models.CharField(blank=True, max_length=64)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('report_json', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeShareAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', '查看'), ('download', '下载'), ('denied', '拒绝')], max_length=16)),
                ('ip_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeShareLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('token_hint', models.CharField(blank=True, max_length=12)),
                ('password_hash', models.CharField(blank=True, max_length=255)),
                ('field_policy', models.JSONField(default=dict)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('allow_download', models.BooleanField(default=False)),
                ('download_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='resumesuggestion',
            name='evidence_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='resumeversion',
            name='language',
            field=models.CharField(default='zh-CN', max_length=16),
        ),
        migrations.AlterField(
            model_name='resume',
            name='canonical_schema_version',
            field=models.CharField(default='1.3.1', max_length=20, verbose_name='JSON Resume 版本'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('ready', '可投递'), ('archived', '已归档'), ('processing', '解析中'), ('published', '已发布'), ('parsed', '已解析'), ('failed', '解析失败')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='resumeversion',
            name='schema_version',
            field=models.CharField(default='1.3.1', max_length=20),
        ),
        migrations.CreateModel(
            name='ResumeAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('source', '原始上传'), ('parse_intermediate', '解析中间件'), ('avatar', '简历头像'), ('artifact', '导出文件')], max_length=32)),
                ('file', models.FileField(upload_to='resume-assets/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('mime_type', models.CharField(blank=True, max_length=120)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(db_index=True, max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='resumes.resumeimportjob')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='resumes.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeDesignRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.PositiveIntegerField()),
                ('template_key', models.CharField(default='ats-classic', max_length=48)),
                ('template_version', models.CharField(default='1.0.0', max_length=24)),
                ('language', models.CharField(default='zh-CN', max_length=16)),
                ('page_size', models.CharField(default='A4', max_length=12)),
                ('design_json', models.JSONField(default=dict)),
                ('design_hash', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_design_revisions', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='resumes.resumedesignrevision')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design_revisions', to='resumes.resume')),
            ],
            options={
                'ordering': ['-revision_number'],
            },
        ),
        migrations.CreateModel(
            name='ResumeArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_etag', models.CharField(blank=True, db_index=True, max_length=64)),
                ('preview_input', models.JSONField(blank=True, default=dict)),
                ('preview_design', models.JSONField(blank=True, default=dict)),
                ('format', models.CharField(choices=[('preview', '预览图'), ('pdf', 'PDF'), ('docx', 'DOCX'), ('json', 'JSON Resume')], max_length=16)),
                ('status', models.CharField(choices=[('pending', '等待生成'), ('processing', '生成中'), ('ready', '可用'), ('failed', '生成失败')], db_index=True, default='pending', max_length=16)),
                ('renderer_name', models.CharField(default='rendercv', max_length=80)),
                ('renderer_version', models.CharField(default='2.8', max_length=40)),
                ('cache_key', models.CharField(max_length=64, unique=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('content_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='resumes.resumeversion')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='resumes.resume')),
                ('asset', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artifact', to='resumes.resumeasset')),
                ('design_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='artifacts', to='resumes.resumedesignrevision')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='resume',
            name='current_design_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='resumes.resumedesignrevision', verbose_name='当前设计版本'),
        ),
        migrations.RunPython(backfill_resume_intelligence, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='resume',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='uniq_default_resume_per_user'),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='base_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='drafts', to='resumes.resumeversion'),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='resume',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumedraft',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_drafts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumeevidencelink',
            name='career_fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resume_evidence_links', to='careers.careerfact'),
        ),
        migrations.AddField(
            model_name='resumeevidencelink',
            name='resume_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='resumes.resumeversion'),
        ),
        migrations.AddField(
            model_name='resumequalityreport',
            name='content_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quality_reports', to='resumes.resumeversion'),
        ),
        migrations.AddField(
            model_name='resumequalityreport',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reports', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumesharelink',
            name='content_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_links', to='resumes.resumeversion'),
        ),
        migrations.AddField(
            model_name='resumesharelink',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_share_links', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resumesharelink',
            name='design_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='share_links', to='resumes.resumedesignrevision'),
        ),
        migrations.AddField(
            model_name='resumesharelink',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_links', to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='resumeshareaccess',
            name='share_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='resumes.resumesharelink'),
        ),
        migrations.AddConstraint(
            model_name='resumedesignrevision',
            constraint=models.UniqueConstraint(fields=('resume', 'revision_number'), name='uniq_resume_design_revision'),
        ),
        migrations.AddConstraint(
            model_name='resumeevidencelink',
            constraint=models.UniqueConstraint(fields=('resume_version', 'json_pointer', 'career_fact'), name='uniq_resume_evidence_pointer_fact'),
        ),
    ]
