# Generated by Django 5.2.7 on 2026-08-09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0008_resumedraft_resumeevidencelink_resumequalityreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeOperationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation_type', models.CharField(db_index=True, max_length=80)),
                ('task_key', models.CharField(blank=True, max_length=80)),
                ('instruction', models.TextField(blank=True)),
                ('job_target_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('result_json', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('artifact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_requests', to='resumes.resumeartifact')),
                ('base_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_requests', to='resumes.resumeversion')),
                ('import_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_requests', to='resumes.resumeimportjob')),
                ('quality_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operation_requests', to='resumes.resumequalityreport')),
                ('result_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_requests', to='resumes.resumesuggestion')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_requests', to='resumes.resume')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_operation_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'operation_type', 'created_at'], name='resume_opreq_owner_idx')],
                'constraints': [
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ('artifact__isnull', False),
                                ('operation_type__in', ['resume.preview', 'resume.export', 'resume.share_export']),
                            )
                            | models.Q(('operation_type', 'resume.quality_review'), ('quality_report__isnull', False))
                            | models.Q(
                                ('import_job__isnull', False),
                                ('operation_type__in', ['resume.import', 'resume.import.retry']),
                            )
                            | models.Q(('base_version__isnull', False), ('operation_type', 'resume.suggestion'))
                        ),
                        name='resume_opreq_target_required',
                    ),
                ],
            },
        ),
    ]
