# Generated by Django 5.2.7 on 2026-04-21 04:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_identifier', models.CharField(db_index=True, help_text='文件MD5哈希值，用于断点续传', max_length=64, unique=True, verbose_name='文件唯一标识')),
                ('file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.BigIntegerField(verbose_name='文件总大小(字节)')),
                ('total_chunks', models.IntegerField(verbose_name='总分片数')),
                ('chunk_size', models.IntegerField(default=5242880, verbose_name='分片大小(字节)')),
                ('uploaded_chunks', models.IntegerField(default=0, verbose_name='已上传分片数')),
                ('status', models.CharField(choices=[('uploading', '上传中'), ('completed', '上传完成'), ('merging', '合并中'), ('merged', '已合并'), ('failed', '失败')], default='uploading', max_length=20, verbose_name='状态')),
                ('merged_file_path', models.CharField(blank=True, max_length=512, verbose_name='合并后文件路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_tasks', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '文件上传任务',
                'verbose_name_plural': '文件上传任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoTranscodeTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_file', models.CharField(max_length=512, verbose_name='原始文件路径')),
                ('original_file_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('original_size', models.BigIntegerField(verbose_name='原始文件大小(字节)')),
                ('original_duration', models.FloatField(blank=True, null=True, verbose_name='原始视频时长(秒)')),
                ('transcoded_file', models.CharField(blank=True, max_length=512, verbose_name='转码后文件路径')),
                ('transcoded_size', models.BigIntegerField(blank=True, null=True, verbose_name='转码后文件大小(字节)')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='转码进度(0-100)')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('video_denoise', models.BooleanField(default=True, verbose_name='视频降噪')),
                ('audio_denoise', models.BooleanField(default=True, verbose_name='音频降噪')),
                ('video_denoise_params', models.JSONField(blank=True, default=dict, help_text='hqdn3d滤镜参数: luma_spatial, chroma_spatial, luma_tmp, chroma_tmp', verbose_name='视频降噪参数')),
                ('audio_denoise_params', models.JSONField(blank=True, default=dict, help_text='anlmdn滤镜参数: s, p, r', verbose_name='音频降噪参数')),
                ('crf', models.IntegerField(default=28, help_text='范围0-51, 值越大压缩率越高', verbose_name='视频质量CRF值')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始处理时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('upload_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcode_task', to='video_uploads.fileuploadtask', verbose_name='关联上传任务')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcode_tasks', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '视频转码任务',
                'verbose_name_plural': '视频转码任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField(help_text='从0开始', verbose_name='分片序号')),
                ('chunk_size', models.IntegerField(verbose_name='分片大小(字节)')),
                ('chunk_hash', models.CharField(blank=True, max_length=64, verbose_name='分片MD5')),
                ('temp_path', models.CharField(max_length=512, verbose_name='临时存储路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('upload_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='video_uploads.fileuploadtask', verbose_name='所属上传任务')),
            ],
            options={
                'verbose_name': '文件分片',
                'verbose_name_plural': '文件分片',
                'ordering': ['upload_task', 'chunk_index'],
                'unique_together': {('upload_task', 'chunk_index')},
            },
        ),
    ]
