# Generated by Django 5.2.7 on 2026-07-15 14:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminauditevent',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='adminauditevent',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='sent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='staffinvitation',
            name='status',
            field=models.CharField(choices=[('pending', '待接受'), ('accepted', '已接受'), ('revoked', '已撤销'), ('expired', '已过期')], db_index=True, default='pending', max_length=16),
        ),
        migrations.CreateModel(
            name='MaintenanceNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('scheduled', '已排期'), ('active', '展示中'), ('ended', '已结束')], db_index=True, default='draft', max_length=16)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_notices', to='staff_admin.staffaccount')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(db_index=True, default=False)),
                ('rollout_percentage', models.PositiveSmallIntegerField(default=0)),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='staff_admin.staffaccount')),
            ],
        ),
        migrations.CreateModel(
            name='StaffEmailOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('to_email', models.EmailField(max_length=254)),
                ('template_key', models.CharField(default='staff_invitation', max_length=80)),
                ('encrypted_payload', models.TextField()),
                ('status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '失败')], db_index=True, default='pending', max_length=16)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_events', to='staff_admin.staffinvitation')),
            ],
        ),
        migrations.CreateModel(
            name='BreakGlassGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate_id', models.PositiveBigIntegerField(db_index=True)),
                ('scope', models.CharField(default='candidate.private.read', max_length=80)),
                ('operation_reason', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='break_glass_grants', to='staff_admin.staffaccount')),
            ],
            options={
                'indexes': [models.Index(fields=['account', 'candidate_id', 'expires_at'], name='staff_admin_account_b73c30_idx')],
            },
        ),
        migrations.CreateModel(
            name='StaffRecoveryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(max_length=64)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to='staff_admin.staffaccount')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'code_hash'), name='uniq_staff_recovery_code')],
            },
        ),
    ]
