# Generated by Django 5.2.7 on 2026-07-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff_admin', '0002_adminauditevent_event_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffaccount',
            name='recovery_codes_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
