# Generated by Django 5.0.3 on 2025-09-23 12:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='问题内容')),
                ('sequence', models.IntegerField(verbose_name='问题序号')),
                ('answer_text', models.TextField(blank=True, verbose_name='用户回答文本')),
                ('audio_url', models.CharField(blank=True, max_length=255, verbose_name='回答音频 URL')),
                ('analysis_data', models.JSONField(blank=True, null=True, verbose_name='实时分析数据')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='得分')),
                ('ai_feedback', models.JSONField(blank=True, null=True, verbose_name='AI 反馈内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='回答时间')),
                ('evaluated_at', models.DateTimeField(blank=True, null=True, verbose_name='评估时间')),
            ],
            options={
                'verbose_name': '面试问题',
                'verbose_name_plural': '面试问题',
                'ordering': ['session', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='会话 UUID')),
                ('job_position', models.CharField(max_length=100, verbose_name='目标岗位')),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('medium', '中等'), ('hard', '困难')], default='medium', max_length=20, verbose_name='难度')),
                ('question_count', models.IntegerField(default=5, verbose_name='问题数量')),
                ('status', models.CharField(choices=[('pending', '待开始'), ('running', '进行中'), ('finished', '已完成'), ('canceled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='持续时间 (秒)')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('report', models.JSONField(blank=True, null=True, verbose_name='面试报告')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '面试会话',
                'verbose_name_plural': '面试会话',
                'ordering': ['-created_at'],
            },
        ),
    ]
