# Generated by Django 5.0.3 on 2025-09-20 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='report',
            field=models.JSONField(blank=True, null=True, verbose_name='面试报告'),
        ),
    ]
