# Generated by Django 5.0.3 on 2025-09-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interviewsession_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='analysis_data',
            field=models.JSONField(blank=True, null=True, verbose_name='实时分析数据'),
        ),
    ]
