# Generated by Django 5.2.7 on 2026-04-21 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_initial'),
        ('video_uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='recording_enabled',
            field=models.BooleanField(default=False, verbose_name='是否开启录像'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='video_upload_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='video_uploads.fileuploadtask', verbose_name='视频上传任务'),
        ),
    ]
