# Generated by Django 5.2.7 on 2026-06-26 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0007_interviewagenttrace'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewagenttrace',
            name='input_hash',
            field=models.CharField(blank=True, max_length=64, verbose_name='输入哈希'),
        ),
        migrations.AddField(
            model_name='interviewagenttrace',
            name='model_config_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='模型配置快照'),
        ),
        migrations.AddField(
            model_name='interviewagenttrace',
            name='output_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='输出摘要'),
        ),
        migrations.AddField(
            model_name='interviewagenttrace',
            name='validation_errors',
            field=models.JSONField(blank=True, default=list, verbose_name='校验错误'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='coverage_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='能力覆盖汇总'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='session_plan',
            field=models.JSONField(blank=True, default=dict, verbose_name='本场面试计划快照'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='template_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='模板快照'),
        ),
        migrations.CreateModel(
            name='EvaluationDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='评估数据集名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('visibility', models.CharField(choices=[('shared', '共享'), ('private', '私有')], default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '离线评估数据集',
                'verbose_name_plural': '离线评估数据集',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_position', models.CharField(max_length=120, verbose_name='岗位')),
                ('jd_text', models.TextField(blank=True, verbose_name='JD')),
                ('resume_text', models.TextField(blank=True, verbose_name='匿名化简历')),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(verbose_name='真实匿名化回答')),
                ('contexts', models.JSONField(blank=True, default=list, verbose_name='检索上下文')),
                ('expected_dimensions', models.JSONField(blank=True, default=list, verbose_name='期望能力标签')),
                ('expected_follow_up', models.TextField(blank=True, verbose_name='期望追问方向')),
                ('ground_truth', models.TextField(blank=True, verbose_name='参考答案/真值')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='interviews.evaluationdataset')),
            ],
            options={
                'verbose_name': '离线评估样例',
                'verbose_name_plural': '离线评估样例',
                'ordering': ['dataset', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待运行'), ('running', '运行中'), ('succeeded', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20)),
                ('config_snapshot', models.JSONField(blank=True, default=dict, verbose_name='配置快照')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='评估摘要')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='interviews.evaluationdataset')),
            ],
            options={
                'verbose_name': '离线评估运行',
                'verbose_name_plural': '离线评估运行',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EvaluationRunMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100, verbose_name='指标名称')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='指标值')),
                ('detail', models.JSONField(blank=True, default=dict, verbose_name='指标详情')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='run_metrics', to='interviews.evaluationcase')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='interviews.evaluationrun')),
            ],
            options={
                'verbose_name': '离线评估指标',
                'verbose_name_plural': '离线评估指标',
                'ordering': ['run', 'metric_name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='量表名称')),
                ('description', models.TextField(blank=True, verbose_name='量表说明')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('visibility', models.CharField(choices=[('system', '系统内置'), ('shared', '共享'), ('private', '私有')], default='private', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_rubrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '面试评分量表',
                'verbose_name_plural': '面试评分量表',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewCalibrationCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='校准样例标题')),
                ('job_position', models.CharField(max_length=120, verbose_name='岗位')),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(verbose_name='匿名化真实回答')),
                ('expected_scores', models.JSONField(blank=True, default=dict, verbose_name='期望评分')),
                ('expected_dimensions', models.JSONField(blank=True, default=list, verbose_name='期望能力标签')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_calibration_cases', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibration_cases', to='interviews.interviewrubric')),
            ],
            options={
                'verbose_name': '面试评分校准样例',
                'verbose_name_plural': '面试评分校准样例',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='模板名称')),
                ('description', models.TextField(blank=True, verbose_name='模板说明')),
                ('job_keywords', models.JSONField(blank=True, default=list, verbose_name='岗位匹配关键词')),
                ('visibility', models.CharField(choices=[('system', '系统内置'), ('shared', '共享'), ('private', '私有')], default='private', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='是否启用')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='版本')),
                ('require_rag', models.BooleanField(default=False, verbose_name='是否强制要求知识库依据')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='模板配置')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_templates', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='templates', to='interviews.interviewrubric')),
            ],
            options={
                'verbose_name': '面试模板',
                'verbose_name_plural': '面试模板',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='evaluationrun',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluation_runs', to='interviews.interviewtemplate'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='interviews.interviewtemplate', verbose_name='面试模板'),
        ),
        migrations.CreateModel(
            name='RubricDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=80, verbose_name='维度标识')),
                ('name', models.CharField(max_length=120, verbose_name='维度名称')),
                ('description', models.TextField(blank=True, verbose_name='维度说明')),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='权重')),
                ('min_coverage', models.PositiveIntegerField(default=1, verbose_name='最低覆盖次数')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('rule_config', models.JSONField(blank=True, default=dict, verbose_name='规则评分配置')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dimensions', to='interviews.interviewrubric')),
            ],
            options={
                'verbose_name': '评分维度',
                'verbose_name_plural': '评分维度',
                'ordering': ['rubric', 'order', 'id'],
                'unique_together': {('rubric', 'key')},
            },
        ),
        migrations.CreateModel(
            name='RubricLevelAnchor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30, verbose_name='等级')),
                ('min_score', models.PositiveIntegerField(default=0, verbose_name='最低分')),
                ('max_score', models.PositiveIntegerField(default=100, verbose_name='最高分')),
                ('description', models.TextField(verbose_name='等级描述')),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='interviews.rubricdimension')),
            ],
            options={
                'verbose_name': '评分等级锚点',
                'verbose_name_plural': '评分等级锚点',
                'ordering': ['dimension', 'min_score'],
            },
        ),
        migrations.CreateModel(
            name='InterviewTemplateStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(max_length=32, verbose_name='阶段标识')),
                ('name', models.CharField(max_length=80, verbose_name='阶段名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('question_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='题量占比')),
                ('target_dimensions', models.JSONField(blank=True, default=list, verbose_name='目标能力维度')),
                ('question_guidance', models.TextField(blank=True, verbose_name='出题指引')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='interviews.interviewtemplate')),
            ],
            options={
                'verbose_name': '面试模板阶段',
                'verbose_name_plural': '面试模板阶段',
                'ordering': ['template', 'order', 'id'],
                'unique_together': {('template', 'stage_key')},
            },
        ),
    ]
