# Generated by Django 5.2.7 on 2026-06-27 05:01

import django.db.models.deletion
import interviews.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_interviewagenttrace_input_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewMediaArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('artifact_type', models.CharField(choices=[('answer_audio', '回答音频'), ('question_tts', '问题语音')], db_index=True, max_length=32)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20)),
                ('source_file', models.FileField(blank=True, null=True, upload_to=interviews.models.interview_media_upload_path)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('transcript_text', models.TextField(blank=True)),
                ('transcript_segments', models.JSONField(blank=True, default=list)),
                ('asr_confidence', models.FloatField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('model_slug', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_artifacts', to='interviews.interviewquestion', verbose_name='关联问题')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_artifacts', to='interviews.interviewsession', verbose_name='面试会话')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_media_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '面试多媒体记录',
                'verbose_name_plural': '面试多媒体记录',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'artifact_type', 'status'], name='interviews__session_3fa0ab_idx'), models.Index(fields=['user', 'created_at'], name='interviews__user_id_26b710_idx')],
            },
        ),
    ]
