# Generated by Django 5.2.7 on 2026-07-04 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_interviewmediaartifact'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAgentMemoryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('observation', '观察'), ('plan', '计划'), ('coverage', '覆盖'), ('question', '题目'), ('environment', '环境')], db_index=True, max_length=30)),
                ('memory_key', models.CharField(db_index=True, max_length=120, verbose_name='记忆键')),
                ('value_summary', models.JSONField(blank=True, default=dict, verbose_name='记忆摘要')),
                ('importance', models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='重要性')),
                ('source_node', models.CharField(blank=True, db_index=True, max_length=80, verbose_name='来源节点')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_memory_events', to='interviews.interviewquestion', verbose_name='关联问题')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_memory_events', to='interviews.interviewsession', verbose_name='面试会话')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_events', to='interviews.interviewagenttrace', verbose_name='关联轨迹')),
            ],
            options={
                'verbose_name': '面试Agent记忆事件',
                'verbose_name_plural': '面试Agent记忆事件',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'event_type', 'importance'], name='interviews__session_67bc7b_idx'), models.Index(fields=['session', 'memory_key', 'created_at'], name='interviews__session_c54cc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='InterviewAgentToolCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(blank=True, db_index=True, max_length=50, verbose_name='事件')),
                ('node_name', models.CharField(db_index=True, max_length=80, verbose_name='节点名称')),
                ('tool_name', models.CharField(db_index=True, max_length=120, verbose_name='工具名称')),
                ('status', models.CharField(choices=[('success', '成功'), ('degraded', '降级'), ('failed', '失败')], db_index=True, default='success', max_length=20)),
                ('input_summary', models.JSONField(blank=True, default=dict, verbose_name='输入摘要')),
                ('output_summary', models.JSONField(blank=True, default=dict, verbose_name='输出摘要')),
                ('retrieval_trace', models.JSONField(blank=True, default=dict, verbose_name='检索轨迹')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('latency_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='耗时毫秒')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tool_calls', to='interviews.interviewquestion', verbose_name='关联问题')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tool_calls', to='interviews.interviewsession', verbose_name='面试会话')),
                ('trace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_calls', to='interviews.interviewagenttrace', verbose_name='关联轨迹')),
            ],
            options={
                'verbose_name': '面试Agent工具调用',
                'verbose_name_plural': '面试Agent工具调用',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session', 'tool_name', 'status'], name='interviews__session_fbf87d_idx'), models.Index(fields=['session', 'node_name', 'created_at'], name='interviews__session_f5947e_idx')],
            },
        ),
    ]
