# Generated by Django 5.2.7 on 2026-07-05 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0010_interviewagentmemoryevent_interviewagenttoolcall'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestionGenerationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='目标题号')),
                ('status', models.CharField(choices=[('pending', '待生成'), ('running', '生成中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20)),
                ('request_hash', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='请求哈希')),
                ('engine_name', models.CharField(blank=True, max_length=40, verbose_name='Agent引擎')),
                ('partial_text', models.TextField(blank=True, verbose_name='部分生成文本')),
                ('final_text', models.TextField(blank=True, verbose_name='最终生成文本')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_generation_jobs', to='interviews.interviewquestion', verbose_name='已回答问题')),
                ('generated_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generation_jobs', to='interviews.interviewquestion', verbose_name='生成的问题')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_generation_jobs', to='interviews.interviewsession', verbose_name='面试会话')),
            ],
            options={
                'verbose_name': '面试下一题生成任务',
                'verbose_name_plural': '面试下一题生成任务',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status', 'updated_at'], name='interviews__session_5fe848_idx'), models.Index(fields=['request_hash'], name='interviews__request_c5a616_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'sequence'), name='uniq_interview_generation_job_sequence')],
            },
        ),
    ]
