# Generated by Codex on 2026-07-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0011_interviewquestiongenerationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewagenttrace',
            name='compressed_context_summary',
            field=models.JSONField(blank=True, default=dict, verbose_name='压缩上下文摘要'),
        ),
        migrations.AddField(
            model_name='interviewagenttrace',
            name='context_budget',
            field=models.JSONField(blank=True, default=dict, verbose_name='上下文预算'),
        ),
        migrations.AddField(
            model_name='interviewagenttrace',
            name='loop_iteration',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Agent Loop轮次'),
        ),
        migrations.AddField(
            model_name='interviewagenttrace',
            name='prompt_version',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='Prompt版本'),
        ),
        migrations.AddField(
            model_name='interviewagenttrace',
            name='subagent_name',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='主导SubAgent'),
        ),
        migrations.AddField(
            model_name='interviewagenttoolcall',
            name='fallback_reason',
            field=models.CharField(blank=True, max_length=200, verbose_name='降级原因'),
        ),
        migrations.AddField(
            model_name='interviewagenttoolcall',
            name='permission_scope',
            field=models.CharField(blank=True, max_length=40, verbose_name='权限范围'),
        ),
        migrations.AddField(
            model_name='interviewagenttoolcall',
            name='subagent_name',
            field=models.CharField(blank=True, db_index=True, max_length=80, verbose_name='调用SubAgent'),
        ),
    ]
