# Generated by Django 5.2.7 on 2026-07-13 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0013_composite_agent_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='experience_mode',
            field=models.CharField(choices=[('realistic', '真实模拟'), ('coaching', '训练指导')], default='realistic', max_length=20, verbose_name='体验模式'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='interview_mode',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='面试模式'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='progress_mode',
            field=models.CharField(default='question_count', max_length=32, verbose_name='进度计算模式'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='target_duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='目标时长（分钟）'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='candidate_question_minutes',
            field=models.PositiveIntegerField(default=3, verbose_name='候选人反问预留时长'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='hard_max_duration_minutes',
            field=models.PositiveIntegerField(default=45, verbose_name='最长时长（分钟）'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='interview_mode',
            field=models.CharField(choices=[('relaxed', '宽松交流'), ('strict', '严格追问'), ('fundamentals', '基础知识'), ('project_deep_dive', '项目深挖'), ('project_with_fundamentals', '项目穿插基础知识'), ('system_design', '系统设计'), ('behavioral', '行为面试'), ('structured', '结构化面试')], default='project_with_fundamentals', max_length=40, verbose_name='面试模式'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='max_turns',
            field=models.PositiveIntegerField(default=18, verbose_name='异常保护最大轮次'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='min_duration_minutes',
            field=models.PositiveIntegerField(default=20, verbose_name='最短时长（分钟）'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='min_turns',
            field=models.PositiveIntegerField(default=5, verbose_name='最少有效轮次'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='style_profile',
            field=models.JSONField(blank=True, default=dict, verbose_name='面试风格配置'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='target_duration_minutes',
            field=models.PositiveIntegerField(default=30, verbose_name='目标时长（分钟）'),
        ),
        migrations.AddField(
            model_name='interviewtemplatestage',
            name='allow_topic_return',
            field=models.BooleanField(default=True, verbose_name='允许返回上层话题'),
        ),
        migrations.AddField(
            model_name='interviewtemplatestage',
            name='allowed_question_types',
            field=models.JSONField(blank=True, default=list, verbose_name='允许题型'),
        ),
        migrations.AddField(
            model_name='interviewtemplatestage',
            name='entry_condition',
            field=models.JSONField(blank=True, default=dict, verbose_name='进入条件'),
        ),
        migrations.AddField(
            model_name='interviewtemplatestage',
            name='exit_condition',
            field=models.JSONField(blank=True, default=dict, verbose_name='退出条件'),
        ),
        migrations.AddField(
            model_name='interviewtemplatestage',
            name='max_duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='阶段最长时长（分钟）'),
        ),
        migrations.AddField(
            model_name='interviewtemplatestage',
            name='min_duration_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='阶段最短时长（分钟）'),
        ),
        migrations.AddField(
            model_name='interviewtemplatestage',
            name='min_verified_dimensions',
            field=models.PositiveIntegerField(default=0, verbose_name='最低验证能力数'),
        ),
        migrations.AlterField(
            model_name='interviewsession',
            name='current_stage',
            field=models.CharField(choices=[('opening', '开场定位'), ('self_intro', '自我介绍'), ('project_anchor', '项目定位'), ('project_deep_dive', '项目深挖'), ('fundamentals_probe', '基础知识验证'), ('role_specific', '岗位专项'), ('system_design', '系统设计'), ('behavioral', '行为面试'), ('candidate_questions', '候选人反问'), ('closing', '自然收尾'), ('resume_deep_dive', '简历深挖'), ('technical_deep_dive', '技术深挖'), ('scenario_challenge', '场景挑战'), ('wrap_up', '收尾复盘')], default='opening', max_length=32, verbose_name='当前面试阶段'),
        ),
    ]
