# Generated by Django 5.2.7 on 2026-07-13 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
        ('interviews', '0014_interviewsession_experience_mode_and_more'),
        ('resumes', '0006_alter_education_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='jd_snapshot',
            field=models.TextField(blank=True, verbose_name='JD 快照'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='job_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='careers.jobtarget', verbose_name='求职目标'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='resume_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='简历快照'),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='resume_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='resumes.resumeversion', verbose_name='简历版本快照来源'),
        ),
    ]
