# Generated by Django 5.2.7 on 2026-07-13 12:58

from django.db import migrations, models


def backfill_last_activity(apps, schema_editor):
    InterviewSession = apps.get_model('interviews', 'InterviewSession')
    for session in InterviewSession.objects.filter(last_activity_at__isnull=True).iterator():
        session.last_activity_at = session.updated_at or session.started_at or session.created_at
        session.save(update_fields=['last_activity_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0015_interviewsession_jd_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='最后活动时间'),
        ),
        migrations.RunPython(backfill_last_activity, migrations.RunPython.noop),
    ]
