# Generated by Django 5.2.7 on 2026-07-19 03:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0016_interviewsession_last_activity_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAgentExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.UUIDField(db_index=True, verbose_name='LangGraph Thread ID')),
                ('run_id', models.UUIDField(unique=True, verbose_name='LangGraph Run ID')),
                ('event', models.CharField(db_index=True, max_length=50, verbose_name='业务事件')),
                ('idempotency_key', models.CharField(max_length=128, verbose_name='幂等键')),
                ('request_hash', models.CharField(db_index=True, max_length=64, verbose_name='请求哈希')),
                ('checkpoint_namespace', models.CharField(blank=True, max_length=180, verbose_name='Checkpoint命名空间')),
                ('engine_version', models.CharField(db_index=True, default='composite_v4', max_length=40)),
                ('state_schema_version', models.PositiveSmallIntegerField(default=4)),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('waiting', '等待生成或恢复'), ('completed', '已完成'), ('degraded', '降级完成'), ('failed', '执行失败'), ('canceled', '已取消')], db_index=True, default='pending', max_length=20)),
                ('fallback_reason', models.CharField(blank=True, max_length=200)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('last_event_id', models.CharField(blank=True, max_length=160)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_run', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='execution', to='interviews.interviewagentrun', verbose_name='兼容运行记录')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_executions', to='interviews.interviewsession', verbose_name='面试会话')),
                ('trigger_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_executions', to='interviews.interviewquestion', verbose_name='触发问题')),
            ],
            options={
                'verbose_name': '面试Agent执行映射',
                'verbose_name_plural': '面试Agent执行映射',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'status', 'updated_at'], name='interviews__session_f64406_idx'), models.Index(fields=['thread_id', 'created_at'], name='interviews__thread__d137c8_idx')],
                'constraints': [models.UniqueConstraint(fields=('session', 'event', 'idempotency_key'), name='uniq_agent_execution_idempotency')],
            },
        ),
    ]
