# Generated by Django 5.2.7 on 2026-07-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0019_unique_question_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewagentmemoryevent',
            name='dedup_key',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='记忆去重键'),
        ),
        migrations.AddField(
            model_name='interviewagentmemoryevent',
            name='last_recalled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后召回时间'),
        ),
        migrations.AddField(
            model_name='interviewagentmemoryevent',
            name='recall_count',
            field=models.PositiveIntegerField(default=0, verbose_name='召回次数'),
        ),
        migrations.AddConstraint(
            model_name='interviewagentmemoryevent',
            constraint=models.UniqueConstraint(condition=models.Q(('dedup_key__isnull', False)), fields=('session', 'dedup_key'), name='uniq_interview_memory_event_dedup'),
        ),
    ]
