# Generated by Django 5.2.7 on 2026-07-23 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0020_interviewagentmemoryevent_dedup_key_and_more'),
        ('staff_admin', '0003_staffaccount_recovery_codes_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentConfigKnowledgeBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfigProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('scope', models.CharField(choices=[('platform', '平台默认'), ('template', '模板覆盖')], db_index=True, default='template', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['scope', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgentConfigRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('approved', '已审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('superseded', '已替代')], db_index=True, default='draft', max_length=24)),
                ('context_mode', models.CharField(choices=[('inherit', '继承平台配置'), ('replace', '完整替换')], default='replace', max_length=16)),
                ('context_policy', models.JSONField(blank=True, default=dict)),
                ('knowledge_mode', models.CharField(choices=[('inherit', '继承平台配置'), ('replace', '完整替换')], default='inherit', max_length=16)),
                ('config_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('evaluation_summary', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['profile', '-version'],
            },
        ),
        migrations.CreateModel(
            name='AgentPromptTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_key', models.CharField(db_index=True, max_length=120)),
                ('system_template', models.TextField()),
                ('user_template', models.TextField()),
                ('variable_schema', models.JSONField(blank=True, default=dict)),
                ('output_contract', models.JSONField(blank=True, default=dict)),
                ('temperature', models.DecimalField(decimal_places=2, default=0.3, max_digits=3)),
                ('max_output_tokens', models.PositiveIntegerField(default=800)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['revision', 'task_key'],
            },
        ),
        migrations.AddField(
            model_name='evaluationcase',
            name='expected_document_revision_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='期望命中的文档修订'),
        ),
        migrations.AddField(
            model_name='evaluationcase',
            name='expected_topics',
            field=models.JSONField(blank=True, default=list, verbose_name='期望主题'),
        ),
        migrations.AddField(
            model_name='evaluationcase',
            name='irrelevant_document_revision_ids',
            field=models.JSONField(blank=True, default=list, verbose_name='无关文档修订'),
        ),
        migrations.AddField(
            model_name='evaluationcase',
            name='is_no_answer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='无答案样例'),
        ),
        migrations.AddField(
            model_name='interviewagentrun',
            name='agent_config_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='interviewagentrun',
            name='agent_config_revision_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewagentrun',
            name='context_envelope_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='interviewagentrun',
            name='context_token_usage',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewagentrun',
            name='prompt_hashes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='agent_config_snapshot',
            field=models.JSONField(blank=True, default=dict, verbose_name='Agent配置快照'),
        ),
        migrations.CreateModel(
            name='AgentConfigEvaluationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evaluation_type', models.CharField(db_index=True, default='full', max_length=32)),
                ('status', models.CharField(choices=[('pending', '待运行'), ('running', '运行中'), ('succeeded', '成功'), ('failed', '失败')], db_index=True, default='pending', max_length=20)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('result_samples', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True)),
                ('revision_hash', models.CharField(db_index=True, max_length=64)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_config_evaluation_runs', to='staff_admin.staffaccount')),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_config_evaluation_runs', to='interviews.evaluationdataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
