# Generated by Django 5.2.7 on 2026-07-23 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0021_agentconfigknowledgebinding_agentconfigprofile_and_more'),
        ('knowledge', '0008_knowledgebase_knowledgebaserevision_and_more'),
        ('staff_admin', '0003_staffaccount_recovery_codes_confirmed_at'),
        ('system', '0009_modeldeployment_tokenizer_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentconfigknowledgebinding',
            name='knowledge_base_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_config_bindings', to='knowledge.knowledgebaserevision'),
        ),
        migrations.AddField(
            model_name='agentconfigknowledgebinding',
            name='retrieval_profile_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_config_overrides', to='knowledge.retrievalprofilerevision'),
        ),
        migrations.AddField(
            model_name='agentconfigprofile',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_config_profiles', to='staff_admin.staffaccount'),
        ),
        migrations.AddField(
            model_name='interviewtemplate',
            name='agent_config_profile',
            field=models.ForeignKey(blank=True, limit_choices_to={'scope': 'template'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_templates', to='interviews.agentconfigprofile', verbose_name='Agent配置覆盖'),
        ),
        migrations.AddField(
            model_name='agentconfigrevision',
            name='approved_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_agent_config_revisions', to='staff_admin.staffaccount'),
        ),
        migrations.AddField(
            model_name='agentconfigrevision',
            name='base_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_revisions', to='interviews.agentconfigrevision'),
        ),
        migrations.AddField(
            model_name='agentconfigrevision',
            name='created_by_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_agent_config_revisions', to='staff_admin.staffaccount'),
        ),
        migrations.AddField(
            model_name='agentconfigrevision',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='interviews.agentconfigprofile'),
        ),
        migrations.AddField(
            model_name='agentconfigprofile',
            name='active_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='interviews.agentconfigrevision'),
        ),
        migrations.AddField(
            model_name='agentconfigknowledgebinding',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_bindings', to='interviews.agentconfigrevision'),
        ),
        migrations.AddField(
            model_name='agentconfigevaluationrun',
            name='baseline_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baseline_config_evaluation_runs', to='interviews.agentconfigrevision'),
        ),
        migrations.AddField(
            model_name='agentconfigevaluationrun',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_evaluation_runs', to='interviews.agentconfigrevision'),
        ),
        migrations.AddField(
            model_name='agentprompttemplate',
            name='model_alias',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_prompt_templates', to='system.modelalias'),
        ),
        migrations.AddField(
            model_name='agentprompttemplate',
            name='revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='interviews.agentconfigrevision'),
        ),
        migrations.AddConstraint(
            model_name='agentconfigrevision',
            constraint=models.UniqueConstraint(fields=('profile', 'version'), name='uniq_agent_config_revision'),
        ),
        migrations.AddConstraint(
            model_name='agentconfigprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('scope', 'platform')), fields=('scope',), name='uniq_platform_agent_config_profile'),
        ),
        migrations.AddConstraint(
            model_name='agentconfigknowledgebinding',
            constraint=models.UniqueConstraint(fields=('revision', 'knowledge_base_revision'), name='uniq_agent_config_knowledge_binding'),
        ),
        migrations.AddConstraint(
            model_name='agentprompttemplate',
            constraint=models.UniqueConstraint(fields=('revision', 'task_key'), name='uniq_agent_prompt_task_revision'),
        ),
    ]
