# Generated by Django 5.2.7 on 2026-07-13 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=48)),
                ('stage', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('saved', '待投递'), ('applied', '已投递'), ('screening', '筛选中'), ('interview', '面试中'), ('offer', '已获 Offer'), ('accepted', '已接受'), ('rejected', '未通过'), ('withdrawn', '已撤回')], db_index=True, default='saved', max_length=24)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('next_action_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='JobTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position_name', models.CharField(max_length=200)),
                ('jd_text', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('active', '准备中'), ('archived', '已归档')], db_index=True, default='active', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('dimension', models.CharField(blank=True, max_length=100)),
                ('priority', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=12)),
                ('status', models.CharField(choices=[('todo', '待完成'), ('doing', '进行中'), ('done', '已完成')], db_index=True, default='todo', max_length=12)),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'priority', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CareerFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fact_type', models.CharField(choices=[('summary', '个人总结'), ('education', '教育经历'), ('work', '工作经历'), ('project', '项目经历'), ('skill', '技能'), ('certification', '证书'), ('achievement', '成果'), ('open_source', '开源经历')], db_index=True, max_length=24)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('source_type', models.CharField(choices=[('manual', '人工录入'), ('resume_import', '简历导入'), ('github', 'GitHub'), ('interview', '面试复盘')], default='manual', max_length=24)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('source_metadata', models.JSONField(blank=True, default=dict)),
                ('verification_status', models.CharField(choices=[('draft', '待确认'), ('confirmed', '已确认'), ('rejected', '已拒绝')], db_index=True, default='draft', max_length=16)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_facts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fact_type', '-updated_at'],
            },
        ),
    ]
