# Generated by Django 5.2.7 on 2026-07-13 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('interviews', '0015_interviewsession_jd_snapshot_and_more'),
        ('resumes', '0006_alter_education_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='resume_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='resumes.resumeversion'),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicationevent',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='careers.jobapplication'),
        ),
        migrations.AddField(
            model_name='jobtarget',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_targets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.jobtarget'),
        ),
        migrations.AddField(
            model_name='learningtask',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_tasks', to='careers.jobapplication'),
        ),
        migrations.AddField(
            model_name='learningtask',
            name='interview_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_tasks', to='interviews.interviewsession'),
        ),
        migrations.AddField(
            model_name='learningtask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_learning_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='careerfact',
            index=models.Index(fields=['user', 'fact_type', 'verification_status'], name='careers_car_user_id_55b9f6_idx'),
        ),
        migrations.AddIndex(
            model_name='jobapplication',
            index=models.Index(fields=['user', 'status', 'next_action_at'], name='careers_job_user_id_22996c_idx'),
        ),
    ]
