# Generated by Django 5.2.7 on 2026-07-13 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0005_backfill_counts'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=160, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('received', '已接收'), ('processed', '已处理'), ('ignored', '已忽略'), ('failed', '失败')], db_index=True, default='received', max_length=16)),
                ('error_message', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='CommunityIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discourse_user_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('discourse_username', models.CharField(blank=True, max_length=120)),
                ('trust_level', models.PositiveSmallIntegerField(default=0)),
                ('reputation', models.IntegerField(default=0)),
                ('profile_snapshot', models.JSONField(blank=True, default=dict)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunityTopicLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discourse_topic_id', models.PositiveIntegerField(unique=True)),
                ('topic_slug', models.SlugField(blank=True, max_length=240)),
                ('topic_url', models.URLField(blank=True, max_length=500)),
                ('embed_url', models.URLField(blank=True, max_length=500)),
                ('last_posted_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('post', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_topic', to='blog.post')),
            ],
        ),
    ]
