# Generated by Django 5.2.7 on 2026-07-26 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_challenge_topic_communitycontent_communitycomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('reactions', models.PositiveIntegerField(default=0)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='community.communitycontent')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content', 'date'), name='uniq_community_content_daily_metric')],
            },
        ),
    ]
