# Generated by Django 5.2.7 on 2026-07-13 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.CharField(blank=True, max_length=80, verbose_name='求职状态'),
        ),
        migrations.AddField(
            model_name='user',
            name='headline',
            field=models.CharField(blank=True, max_length=160, verbose_name='职业标题'),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=120, verbose_name='所在地区'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_visibility',
            field=models.CharField(choices=[('private', '仅自己'), ('community', '社区可见'), ('public', '公开')], default='private', max_length=16, verbose_name='资料可见性'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills_profile',
            field=models.JSONField(blank=True, default=list, verbose_name='技能画像'),
        ),
        migrations.AddField(
            model_name='user',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, verbose_name='目标岗位'),
        ),
        migrations.AddField(
            model_name='user',
            name='years_experience',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='工作年限'),
        ),
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('refresh_jti', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('expires_at', models.DateTimeField()),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('event', models.CharField(db_index=True, max_length=32)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('reason', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('interview_reminders', models.BooleanField(default=True)),
                ('application_updates', models.BooleanField(default=True)),
                ('community_updates', models.BooleanField(default=True)),
                ('direct_messages', models.BooleanField(default=True)),
                ('digest_frequency', models.CharField(choices=[('none', '不汇总'), ('daily', '每日'), ('weekly', '每周')], default='weekly', max_length=16)),
                ('quiet_hours', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('export', '导出数据'), ('delete', '注销账号')], max_length=16)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('completed', '已完成'), ('rejected', '已拒绝')], db_index=True, default='pending', max_length=16)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
