# Generated by Django 5.2.7 on 2026-07-13 12:58

from django.db import migrations, models
from django.utils import timezone


def mark_existing_users_onboarded(apps, schema_editor):
    User = apps.get_model('users', 'User')
    User.objects.filter(onboarding_completed_at__isnull=True).update(
        onboarding_step='completed',
        onboarding_completed_at=timezone.now(),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_availability_user_headline_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='新手引导完成时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='新手引导步骤'),
        ),
        migrations.RunPython(mark_existing_users_onboarded, migrations.RunPython.noop),
    ]
