# Generated by Django 5.2.7 on 2026-07-15 14:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_onboarding_completed_at_user_onboarding_step'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(db_index=True, default='github', max_length=32)),
                ('flow', models.CharField(choices=[('login', '登录或注册'), ('connect', '绑定账号')], default='login', max_length=16)),
                ('status', models.CharField(choices=[('pending', '等待授权'), ('processing', '处理中'), ('link_required', '等待账号确认'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=20)),
                ('state_hash', models.CharField(max_length=64, unique=True)),
                ('code_verifier', models.CharField(max_length=160)),
                ('redirect_uri', models.URLField(max_length=500)),
                ('return_to', models.CharField(default='/dashboard', max_length=300)),
                ('provider_uid', models.CharField(blank=True, db_index=True, max_length=160)),
                ('verified_email', models.EmailField(blank=True, max_length=254)),
                ('profile_data', models.JSONField(blank=True, default=dict)),
                ('link_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oauth_flows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'status', 'expires_at'], name='users_oauth_provide_b5ee17_idx')],
            },
        ),
    ]
