<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { api } from '@/api';
const loading = ref(false); const rows = ref<any[]>([]); const detail=ref<any>(null); const drawer=ref(false);
const load = async () => { loading.value = true; try { rows.value = await api.get('/agent-runs/'); } finally { loading.value = false; } };
const open=async(row:any)=>{detail.value=await api.get(`/agent-runs/${row.run_id}/`);drawer.value=true};
onMounted(load);
</script>
<template><div class="page" v-loading="loading"><header class="page-header"><div><h1>Agent 运行审计</h1><p>按节点查看 SubAgent、工具调用、检索证据、重试和降级，不返回敏感 Prompt 或密钥。</p></div><el-button @click="load">刷新</el-button></header><div class="data-surface" style="margin-top:18px"><el-table :data="rows"><el-table-column prop="run_id" label="Run ID" min-width="250" /><el-table-column prop="event" label="事件" width="150" /><el-table-column prop="status" label="状态" width="110" /><el-table-column prop="current_node" label="当前节点" min-width="170" /><el-table-column prop="attempt_count" label="尝试" width="70" /><el-table-column prop="fallback_reason" label="降级原因" min-width="220" show-overflow-tooltip /><el-table-column label="操作" width="90"><template #default="{row}"><el-button link type="primary" @click="open(row)">详情</el-button></template></el-table-column></el-table></div>
<el-drawer v-model="drawer" title="Agent Run 节点时间线" size="860px"><template v-if="detail"><el-descriptions :column="3" border><el-descriptions-item label="Run ID">{{detail.run_id}}</el-descriptions-item><el-descriptions-item label="引擎">{{detail.engine_name}}</el-descriptions-item><el-descriptions-item label="状态">{{detail.status}}</el-descriptions-item><el-descriptions-item label="候选人">{{detail.candidate_email}}</el-descriptions-item><el-descriptions-item label="事件">{{detail.event}}</el-descriptions-item><el-descriptions-item label="Prompt 版本">{{detail.prompt_version||'-'}}</el-descriptions-item></el-descriptions><el-alert v-if="detail.fallback_reason||detail.error_message" class="run-alert" type="warning" :title="detail.fallback_reason||'运行异常'" :description="detail.error_message" :closable="false" /><h3>节点执行</h3><el-timeline><el-timeline-item v-for="node in detail.nodes" :key="node.id" :timestamp="`${node.subagent_name} · ${node.latency_ms??'-'}ms`" :type="node.status==='succeeded'?'success':node.status==='failed'?'danger':'warning'"><div class="node-card"><strong>{{node.node_name}} #{{node.attempt}}</strong><el-tag size="small">{{node.status}}</el-tag><pre>{{JSON.stringify(node.output_summary,null,2)}}</pre><small v-if="node.fallback_reason">降级：{{node.fallback_reason}}</small></div></el-timeline-item></el-timeline><h3>Trace 与工具调用</h3><el-collapse><el-collapse-item v-for="trace in detail.traces" :key="trace.id" :title="`${trace.event} · ${trace.subagent_name||'CompositeAgent'}`"><pre class="trace-json">{{JSON.stringify({question_plan:trace.question_plan,rag_context:trace.rag_context,context_budget:trace.context_budget,validation_errors:trace.validation_errors},null,2)}}</pre><el-table :data="trace.tool_calls" size="small"><el-table-column prop="tool_name" label="工具" /><el-table-column prop="subagent_name" label="SubAgent" /><el-table-column prop="status" label="状态" width="90" /><el-table-column prop="latency_ms" label="耗时" width="90" /><el-table-column prop="fallback_reason" label="降级" /></el-table></el-collapse-item></el-collapse></template></el-drawer></div></template>
<style scoped>h3{margin:24px 0 12px}.run-alert{margin:18px 0}.node-card{padding:12px;border:1px solid #e1e6ed;background:#fff}.node-card strong{margin-right:10px}.node-card pre,.trace-json{max-height:220px;overflow:auto;padding:12px;background:#f6f8fb;font-size:12px;white-space:pre-wrap}.node-card small{color:#b45309}</style>
