<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { api } from '@/api';

const loading = ref(false); const rows = ref<any[]>([]); const detail=ref<any>(null); const drawer=ref(false); const editDialog=ref(false); const editing=ref<any>(null);
const editForm=reactive({content:'',block_type:'paragraph',is_excluded:false,operation_reason:''});
const load = async () => { loading.value = true; try { rows.value = await api.get('/knowledge-reviews/'); } finally { loading.value = false; } };
const open=async(row:any)=>{detail.value=await api.get(`/knowledge-reviews/${row.id}/`);drawer.value=true};
const refreshDetail=async()=>{if(detail.value)detail.value=await api.get(`/knowledge-reviews/${detail.value.id}/`)};
const decide = async (row: any, decision: 'approve' | 'reject') => { const reason = await ElMessageBox.prompt(decision === 'approve' ? '说明本次审批依据。' : '填写拒绝原因。', decision === 'approve' ? '审批上线' : '拒绝版本', { inputValidator: value => Boolean(value?.trim()) || '必须填写操作原因' }); await api.post(`/knowledge-reviews/${row.id}/${decision}/`, { operation_reason: reason.value.trim() }, { headers: { 'Idempotency-Key': crypto.randomUUID() } }); ElMessage.success(decision === 'approve' ? '已批准并进入索引队列。' : '已拒绝该草稿版本。'); drawer.value=false; await load(); };
const openEdit=(chunk:any)=>{editing.value=chunk;Object.assign(editForm,{content:chunk.content,block_type:chunk.block_type,is_excluded:chunk.is_excluded,operation_reason:''});editDialog.value=true};
const saveChunk=async()=>{await api.patch(`/knowledge-chunk-drafts/${editing.value.id}/`,editForm);editDialog.value=false;ElMessage.success('知识块已更新。');await refreshDetail()};
const chunkAction=async(chunk:any,action:'split'|'merge-next')=>{let position:any=undefined;const {value}=await ElMessageBox.prompt(action==='split'?'输入按字符计算的拆分位置':'说明合并原因',action==='split'?'拆分知识块':'合并下一块',{inputType:action==='split'?'text':'textarea'});if(action==='split')position=Number(value);await api.post(`/knowledge-chunk-drafts/${chunk.id}/${action}/`,{position,operation_reason:action==='split'?'人工调整知识块边界':value},{headers:{'Idempotency-Key':crypto.randomUUID()}});await refreshDetail()};
const toggleExcluded=async(chunk:any)=>{await api.patch(`/knowledge-chunk-drafts/${chunk.id}/`,{is_excluded:!chunk.is_excluded,operation_reason:chunk.is_excluded?'重新纳入检索':'排除低质量知识块'});await refreshDetail()};
const reparse=async()=>{const {value}=await ElMessageBox.prompt('说明重新解析原因','重新解析',{inputType:'textarea'});await api.post(`/knowledge-documents/${detail.value.id}/reparse/`,{operation_reason:value});ElMessage.success('重新解析任务已进入队列。');drawer.value=false;await load()};
onMounted(load);
</script>
<template><div class="page" v-loading="loading"><header class="page-header"><div><h1>知识审批与块编辑</h1><p>审核真实解析结构，逐块修正后再冻结发布版本；仅发布版本进入面试 RAG。</p></div><el-button @click="load">刷新</el-button></header><div class="data-surface" style="margin-top:18px"><el-empty v-if="!rows.length" description="暂无待审核知识版本" /><el-table v-else :data="rows"><el-table-column prop="title" label="文档" min-width="220" /><el-table-column prop="owner" label="所有者" min-width="190" /><el-table-column prop="visibility" label="范围" width="90" /><el-table-column prop="source_type" label="来源" width="120" /><el-table-column prop="chunk_count" label="草稿块" width="90" /><el-table-column prop="parse_status" label="解析状态" width="110" /><el-table-column label="操作" width="220" fixed="right"><template #default="{row}"><el-button link @click="open(row)">审阅与编辑</el-button><el-button link type="primary" @click="decide(row,'approve')">批准</el-button><el-button link type="danger" @click="decide(row,'reject')">拒绝</el-button></template></el-table-column></el-table></div>
<el-drawer v-model="drawer" title="知识修订审阅" size="900px"><template v-if="detail"><el-descriptions :column="3" border><el-descriptions-item label="文档">{{detail.title}}</el-descriptions-item><el-descriptions-item label="解析器">{{detail.parser_name||'-'}} {{detail.parser_version}}</el-descriptions-item><el-descriptions-item label="解析状态">{{detail.parse_status}}</el-descriptions-item><el-descriptions-item label="岗位">{{detail.job_positions.join('、')||'-'}}</el-descriptions-item><el-descriptions-item label="能力标签">{{detail.ability_tags.join('、')||'-'}}</el-descriptions-item><el-descriptions-item label="难度">{{detail.difficulty}}</el-descriptions-item></el-descriptions><el-alert v-if="detail.parser_fallback_reason" type="warning" :title="detail.parser_fallback_reason" :closable="false" style="margin-top:16px" /><div class="drawer-actions"><el-button @click="reparse">重新解析</el-button><el-button type="primary" @click="decide(detail,'approve')">批准并索引</el-button><el-button type="danger" plain @click="decide(detail,'reject')">拒绝版本</el-button></div><h3>结构化知识块（{{detail.draft_revision?.chunks.length||0}}）</h3><div class="chunk-list"><article v-for="chunk in detail.draft_revision?.chunks" :key="chunk.id" :class="['chunk-item',{excluded:chunk.is_excluded}]"><header><div><strong>#{{chunk.order}} {{chunk.block_type}}</strong><span>{{chunk.token_count}} tokens · {{chunk.heading_path.join(' / ')||'无标题路径'}}</span></div><el-tag v-if="chunk.is_excluded" type="warning">已排除</el-tag></header><pre>{{chunk.content}}</pre><div v-if="chunk.table_data?.length" class="table-data"><strong>结构化表格</strong><pre>{{JSON.stringify(chunk.table_data,null,2)}}</pre></div><footer><el-button link type="primary" @click="openEdit(chunk)">编辑</el-button><el-button link @click="chunkAction(chunk,'split')">拆分</el-button><el-button link @click="chunkAction(chunk,'merge-next')">合并下一块</el-button><el-button link :type="chunk.is_excluded?'success':'warning'" @click="toggleExcluded(chunk)">{{chunk.is_excluded?'恢复检索':'排除块'}}</el-button></footer></article></div></template></el-drawer>
<el-dialog v-model="editDialog" title="编辑知识块草稿" width="720px"><el-form label-position="top"><el-form-item label="块类型"><el-select v-model="editForm.block_type"><el-option label="段落" value="paragraph" /><el-option label="表格" value="table" /><el-option label="FAQ" value="faq" /><el-option label="图片 OCR" value="image" /></el-select></el-form-item><el-form-item label="块内容"><el-input v-model="editForm.content" type="textarea" :rows="14" /></el-form-item><el-form-item label="检索状态"><el-switch v-model="editForm.is_excluded" active-text="排除" inactive-text="纳入" /></el-form-item><el-form-item label="编辑原因"><el-input v-model="editForm.operation_reason" type="textarea" /></el-form-item></el-form><template #footer><el-button @click="editDialog=false">取消</el-button><el-button type="primary" :disabled="!editForm.content.trim()||!editForm.operation_reason.trim()" @click="saveChunk">保存</el-button></template></el-dialog></div></template>
<style scoped>.drawer-actions{display:flex;gap:8px;margin:18px 0}h3{margin:24px 0 12px}.chunk-list{display:grid;gap:12px}.chunk-item{border:1px solid #dfe3e8;background:#fff}.chunk-item.excluded{opacity:.62;background:#fafafa}.chunk-item>header{display:flex;justify-content:space-between;padding:12px 14px;border-bottom:1px solid #e5e7eb}.chunk-item header span{display:block;margin-top:4px;color:#667085;font-size:12px}.chunk-item>pre{margin:0;padding:14px;white-space:pre-wrap;line-height:1.65}.chunk-item>footer{padding:8px 14px;border-top:1px solid #e5e7eb}.table-data{margin:0 14px 14px;padding:12px;background:#f6f8fb}.table-data pre{max-height:220px;overflow:auto;font-size:12px}</style>
