# Generated by Django 5.2.7 on 2026-06-27 03:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_knowledgedocument_usage_stats'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='approval_status',
            field=models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('approved', '已上线'), ('rejected', '已拒绝'), ('archived', '已归档')], db_index=True, default='draft', max_length=30, verbose_name='审批状态'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审批通过时间'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_knowledge_documents', to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=20, verbose_name='文件类型'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='拒绝原因'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='knowledge_sources/%Y/%m/', verbose_name='源文件'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交审核时间'),
        ),
        migrations.CreateModel(
            name='KnowledgeImportBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('completed', '已完成'), ('partial_failed', '部分失败'), ('failed', '失败')], db_index=True, default='pending', max_length=30, verbose_name='导入状态')),
                ('source_files', models.JSONField(blank=True, default=list, verbose_name='源文件列表')),
                ('options', models.JSONField(blank=True, default=dict, verbose_name='导入选项')),
                ('total_files', models.PositiveIntegerField(default=0, verbose_name='文件总数')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='成功数')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='失败数')),
                ('error_log', models.JSONField(blank=True, default=list, verbose_name='错误日志')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_import_batches', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
            ],
            options={
                'verbose_name': '知识库导入批次',
                'verbose_name_plural': '知识库导入批次',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='import_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='knowledge.knowledgeimportbatch', verbose_name='导入批次'),
        ),
        migrations.CreateModel(
            name='KnowledgeImportFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_file', models.FileField(upload_to='knowledge_imports/%Y/%m/', verbose_name='上传文件')),
                ('original_name', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('processing', '处理中'), ('imported', '已导入'), ('failed', '失败')], db_index=True, default='pending', max_length=30, verbose_name='处理状态')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_files', to='knowledge.knowledgeimportbatch', verbose_name='导入批次')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_files', to='knowledge.knowledgedocument', verbose_name='生成文档')),
            ],
            options={
                'verbose_name': '知识库导入文件',
                'verbose_name_plural': '知识库导入文件',
                'ordering': ['batch', 'created_at'],
            },
        ),
    ]
