# Generated by Django 5.2.7 on 2026-06-27 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_knowledgedocument_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='block_type',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='块类型'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='chunk_level',
            field=models.PositiveSmallIntegerField(db_index=True, default=1, verbose_name='分片层级'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='内容哈希'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='heading_path',
            field=models.JSONField(blank=True, default=list, verbose_name='标题路径'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='page_end',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='结束页'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='page_start',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='起始页'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='parent_chunk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_chunks', to='knowledge.knowledgechunk', verbose_name='父级分片'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='semantic_group_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='语义组'),
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='token_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Token数量估算'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='ocr_enabled',
            field=models.BooleanField(default=False, verbose_name='是否启用OCR'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='parse_status',
            field=models.CharField(choices=[('pending', '待解析'), ('parsing', '解析中'), ('parsed', '已解析'), ('failed', '解析失败')], db_index=True, default='parsed', max_length=20, verbose_name='解析状态'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='parsed_content',
            field=models.JSONField(blank=True, default=dict, verbose_name='结构化解析结果'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='parser_fallback_reason',
            field=models.TextField(blank=True, verbose_name='解析降级原因'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='parser_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='解析器'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='parser_version',
            field=models.CharField(blank=True, max_length=80, verbose_name='解析器版本'),
        ),
    ]
