# Generated by Django 5.2.7 on 2026-07-13 12:58

import django.db.models.deletion
import hashlib
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_document_revisions(apps, schema_editor):
    KnowledgeDocument = apps.get_model('knowledge', 'KnowledgeDocument')
    KnowledgeDocumentRevision = apps.get_model('knowledge', 'KnowledgeDocumentRevision')
    KnowledgeChunkDraft = apps.get_model('knowledge', 'KnowledgeChunkDraft')
    KnowledgeChunk = apps.get_model('knowledge', 'KnowledgeChunk')

    for document in KnowledgeDocument.objects.all().iterator():
        is_published = document.approval_status == 'approved' and document.status == 'indexed'
        revision = KnowledgeDocumentRevision.objects.create(
            document_id=document.id,
            version_number=1,
            status='published' if is_published else 'draft',
            source_content=document.content or '',
            parsed_content=document.parsed_content or {},
            parser_snapshot={
                'name': document.parser_name or '',
                'version': document.parser_version or '',
                'fallback_reason': document.parser_fallback_reason or '',
                'ocr_enabled': bool(document.ocr_enabled),
            },
            created_by_id=document.created_by_id,
            approved_by_id=document.approved_by_id if is_published else None,
            submitted_at=document.submitted_at if is_published else None,
            approved_at=document.approved_at if is_published else None,
            published_at=document.last_indexed_at if is_published else None,
        )

        chunks = KnowledgeChunk.objects.filter(document_id=document.id)
        preferred = chunks.filter(chunk_level=2)
        source_chunks = preferred if preferred.exists() else chunks
        draft_rows = []
        for order, chunk in enumerate(source_chunks.order_by('chunk_index').iterator()):
            content = (chunk.content or '').strip()
            if not content:
                continue
            metadata = chunk.metadata or {}
            draft_rows.append(KnowledgeChunkDraft(
                revision_id=revision.id,
                order=order,
                block_type=chunk.block_type or 'paragraph',
                heading_path=chunk.heading_path or [],
                page_start=chunk.page_start,
                page_end=chunk.page_end,
                content=content,
                table_data=metadata.get('table_data') or [],
                metadata=metadata,
                token_count=chunk.token_count or max(1, len(content) // 2),
                content_hash=chunk.content_hash or hashlib.sha256(content.encode('utf-8')).hexdigest(),
            ))
        if not draft_rows and (document.content or '').strip():
            content = document.content.strip()
            draft_rows.append(KnowledgeChunkDraft(
                revision_id=revision.id,
                order=0,
                block_type='paragraph',
                content=content,
                token_count=max(1, len(content) // 2),
                content_hash=hashlib.sha256(content.encode('utf-8')).hexdigest(),
            ))
        if draft_rows:
            KnowledgeChunkDraft.objects.bulk_create(draft_rows)

        chunks.update(revision_id=revision.id)
        document.draft_revision_id = revision.id
        if is_published:
            document.published_revision_id = revision.id
        document.save(update_fields=['draft_revision', 'published_revision'])


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_knowledgechunk_block_type_knowledgechunk_chunk_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='knowledgechunk',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='KnowledgeDocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', '编辑中'), ('pending_review', '待审核'), ('approved', '已批准'), ('published', '已发布'), ('rejected', '已拒绝'), ('superseded', '已替换')], db_index=True, default='draft', max_length=24)),
                ('source_content', models.TextField(blank=True)),
                ('parsed_content', models.JSONField(blank=True, default=dict)),
                ('parser_snapshot', models.JSONField(blank=True, default=dict)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_knowledge_revisions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_revisions', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='knowledge.knowledgedocument')),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunkDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('block_type', models.CharField(db_index=True, default='paragraph', max_length=40)),
                ('heading_path', models.JSONField(blank=True, default=list)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('table_data', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('is_excluded', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='knowledge.knowledgechunkdraft')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_drafts', to='knowledge.knowledgedocumentrevision')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='knowledgechunk',
            name='revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='published_chunks', to='knowledge.knowledgedocumentrevision', verbose_name='发布版本'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='draft_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgedocumentrevision', verbose_name='当前编辑版本'),
        ),
        migrations.AddField(
            model_name='knowledgedocument',
            name='published_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgedocumentrevision', verbose_name='当前发布版本'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('revision', 'chunk_index'), name='uniq_knowledge_revision_chunk_index'),
        ),
        migrations.AddConstraint(
            model_name='knowledgedocumentrevision',
            constraint=models.UniqueConstraint(fields=('document', 'version_number'), name='uniq_knowledge_document_revision'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunkdraft',
            constraint=models.UniqueConstraint(fields=('revision', 'order'), name='uniq_knowledge_revision_chunk_order'),
        ),
        migrations.RunPython(backfill_document_revisions, migrations.RunPython.noop),
    ]
