# Generated by Django 5.2.7 on 2026-07-15 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_alter_knowledgechunk_unique_together_and_more'),
        ('staff_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='staff_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_knowledge_documents', to='staff_admin.staffaccount', verbose_name='员工审批人'),
        ),
        migrations.AddField(
            model_name='knowledgedocumentrevision',
            name='staff_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_knowledge_revisions', to='staff_admin.staffaccount'),
        ),
    ]
