# Generated by Django 5.2.7 on 2026-07-23 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_knowledgedocument_staff_approved_by_and_more'),
        ('staff_admin', '0003_staffaccount_recovery_codes_confirmed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('visibility', models.CharField(choices=[('system', '系统'), ('shared', '共享'), ('private', '私有')], default='shared', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_bases', to='staff_admin.staffaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('approved', '已审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('superseded', '已替代')], db_index=True, default='draft', max_length=24)),
                ('ingestion_policy', models.JSONField(blank=True, default=dict)),
                ('config_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_knowledge_base_revisions', to='staff_admin.staffaccount')),
                ('created_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_base_revisions', to='staff_admin.staffaccount')),
                ('knowledge_base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='knowledge.knowledgebase')),
            ],
            options={
                'ordering': ['knowledge_base', '-version'],
            },
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='active_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.knowledgebaserevision'),
        ),
        migrations.CreateModel(
            name='KnowledgeBaseRevisionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_base_bindings', to='knowledge.knowledgedocument')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_bindings', to='knowledge.knowledgebaserevision')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='knowledgebaserevision',
            name='documents',
            field=models.ManyToManyField(related_name='knowledge_base_revisions', through='knowledge.KnowledgeBaseRevisionDocument', to='knowledge.knowledgedocument'),
        ),
        migrations.CreateModel(
            name='RetrievalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retrieval_profiles', to='staff_admin.staffaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RetrievalProfileRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('approved', '已审核'), ('published', '已发布'), ('rejected', '已拒绝'), ('superseded', '已替代')], db_index=True, default='draft', max_length=24)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('config_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('validation_report', models.JSONField(blank=True, default=dict)),
                ('evaluation_summary', models.JSONField(blank=True, default=dict)),
                ('change_summary', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_retrieval_profile_revisions', to='staff_admin.staffaccount')),
                ('created_by_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_retrieval_profile_revisions', to='staff_admin.staffaccount')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='knowledge.retrievalprofile')),
            ],
            options={
                'ordering': ['profile', '-version'],
            },
        ),
        migrations.AddField(
            model_name='retrievalprofile',
            name='active_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='knowledge.retrievalprofilerevision'),
        ),
        migrations.AddField(
            model_name='knowledgebaserevision',
            name='default_retrieval_revision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_base_revisions', to='knowledge.retrievalprofilerevision'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebaserevisiondocument',
            constraint=models.UniqueConstraint(fields=('revision', 'document'), name='uniq_knowledge_base_revision_document'),
        ),
        migrations.AddConstraint(
            model_name='retrievalprofilerevision',
            constraint=models.UniqueConstraint(fields=('profile', 'version'), name='uniq_retrieval_profile_revision'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebaserevision',
            constraint=models.UniqueConstraint(fields=('knowledge_base', 'version'), name='uniq_knowledge_base_revision'),
        ),
    ]
